/**
 * Central registry of production Tauri IPC command names.
 */
export const COMMANDS = {
  GET_APP_INFO: 'get_app_info',
  CHECK_DB_HEALTH: 'check_db_health',
  GET_DB_DIAGNOSTIC: 'get_db_diagnostic',
  GET_SETUP_STATUS: 'get_setup_status',
  BOOTSTRAP_FIRST_ADMIN: 'bootstrap_first_admin',
  LOGIN: 'login',
  LOGOUT: 'logout',
  CREATE_PRODUCT: 'create_product',
  LIST_PRODUCTS: 'list_products',
  CREATE_WAREHOUSE: 'create_warehouse',
  LIST_WAREHOUSES: 'list_warehouses',
  LIST_FISCAL_PERIODS: 'list_fiscal_periods',
  GET_OPEN_FISCAL_PERIOD: 'get_open_fiscal_period',
  GET_DASHBOARD_SUMMARY: 'get_dashboard_summary',
  POST_STOCK_RECEIPT: 'post_stock_receipt',
  GET_INVENTORY_CAPABILITIES: 'get_inventory_capabilities',
  LIST_INVENTORY_SNAPSHOT: 'list_inventory_snapshot',
  CONFIRM_STOCK_ADJUSTMENT: 'confirm_stock_adjustment',
  LIST_STOCK_ADJUSTMENT_UNITS: 'list_stock_adjustment_units',
  OPEN_CASH_SESSION: 'open_cash_session',
  INSPECT_ACTIVE_CASH_SESSION: 'inspect_active_cash_session',
  // Legacy Slice-1 total-close command remains in the TS registry only while
  // older callers compile; PostgreSQL EXECUTE is revoked in S4-002 and the
  // Tauri handler is no longer registered.
  CLOSE_CASH_SESSION: 'close_cash_session',
  GET_CASH_SESSION: 'get_cash_session',
  INSPECT_CURRENT_CASH_SESSION: 'inspect_current_cash_session',
  LIST_CASH_DENOMINATIONS: 'list_cash_denominations',
  BEGIN_CASH_SESSION_CLOSE: 'begin_cash_session_close',
  CANCEL_CASH_SESSION_CLOSE: 'cancel_cash_session_close',
  SUBMIT_CASH_SESSION_COUNT: 'submit_cash_session_count',
  APPROVE_CASH_SESSION_VARIANCE: 'approve_cash_session_variance',
  SUSPEND_CASH_SESSION: 'suspend_cash_session',
  RESUME_CASH_SESSION: 'resume_cash_session',
  HANDOVER_CASH_SESSION: 'handover_cash_session',
  LIST_DRAWER_OPERATION_POLICY: 'list_drawer_operation_policy',
  UPDATE_DRAWER_OPERATION_POLICY: 'update_drawer_operation_policy',
  GET_INVENTORY_CORRECTIONS_SETTING: 'get_inventory_corrections_setting',
  UPDATE_INVENTORY_CORRECTIONS_SETTING: 'update_inventory_corrections_setting',
  // R0 — historical finance onboarding
  GET_HISTORICAL_FINANCE_SETTING: 'get_historical_finance_setting',
  UPDATE_HISTORICAL_FINANCE_SETTING: 'update_historical_finance_setting',
  CREATE_HISTORICAL_FINANCE_BATCH: 'create_historical_finance_batch',
  REPLACE_HISTORICAL_FINANCE_BATCH_DATA: 'replace_historical_finance_batch_data',
  VALIDATE_HISTORICAL_FINANCE_BATCH: 'validate_historical_finance_batch',
  APPROVE_HISTORICAL_FINANCE_BATCH: 'approve_historical_finance_batch',
  GET_HISTORICAL_FINANCE_SUMMARY: 'get_historical_finance_summary',
  // R0-002 — paper-book historical trade onboarding & analytics
  CREATE_HISTORICAL_TRADE_BATCH: 'create_historical_trade_batch',
  REPLACE_HISTORICAL_TRADE_BATCH_DATA: 'replace_historical_trade_batch_data',
  VALIDATE_HISTORICAL_TRADE_BATCH: 'validate_historical_trade_batch',
  APPROVE_HISTORICAL_TRADE_BATCH: 'approve_historical_trade_batch',
  GET_HISTORICAL_TRADE_ANALYTICS: 'get_historical_trade_analytics',
  // R0-005 — historical product description mapping
  GET_HISTORICAL_PRODUCT_MAPPING: 'get_historical_product_mapping',
  GET_HISTORICAL_MAPPING_READINESS: 'get_historical_mapping_readiness',
  APPLY_HISTORICAL_PRODUCT_ALIAS_DECISIONS: 'apply_historical_product_alias_decisions',
  CLEAR_HISTORICAL_PRODUCT_ALIAS: 'clear_historical_product_alias',
  // WS-I-1 — historical financial reports
  GET_HISTORICAL_REPORT: 'get_historical_report',
  GET_HISTORICAL_REPORT_SCOPE: 'get_historical_report_scope',
  // R5 — current opening-state reconciliation and one-time application
  GET_OPENING_STATE_SETTING: 'get_opening_state_setting',
  UPDATE_OPENING_STATE_SETTING: 'update_opening_state_setting',
  CREATE_OPENING_STATE_PACKAGE: 'create_opening_state_package',
  REPLACE_OPENING_STATE_PACKAGE_DATA: 'replace_opening_state_package_data',
  VALIDATE_OPENING_STATE_PACKAGE: 'validate_opening_state_package',
  APPROVE_OPENING_STATE_PACKAGE: 'approve_opening_state_package',
  GET_OPENING_STATE_PACKAGE: 'get_opening_state_package',
  GET_OPENING_STATE_ONBOARDING_STATUS: 'get_opening_state_onboarding_status',
  SET_OPENING_STATE_ONBOARDING_CHOICE: 'set_opening_state_onboarding_choice',
  GET_OPENING_STATE_APPLICATION_CONTEXT: 'get_opening_state_application_context',
  UPDATE_OPENING_STATE_APPLICATION_SETTING: 'update_opening_state_application_setting',
  APPLY_OPENING_STATE: 'apply_opening_state',
  // R6 — backup creation, validation, and temporary restore verification
  GET_RESTORE_VERIFICATION_SETTING: 'get_restore_verification_setting',
  UPDATE_RESTORE_VERIFICATION_SETTING: 'update_restore_verification_setting',
  CREATE_OPERATOR_BACKUP: 'create_operator_backup',
  VALIDATE_OPERATOR_BACKUP: 'validate_operator_backup',
  VERIFY_OPERATOR_BACKUP_RESTORE: 'verify_operator_backup_restore',
  GET_BACKUP_DESTINATION_SETTING: 'get_backup_destination_setting',
  UPDATE_BACKUP_DESTINATION_SETTING: 'update_backup_destination_setting',
  CONFIRM_CASH_SALE: 'confirm_cash_sale',
  GET_SALE_DOCUMENT: 'get_sale_document',
  LIST_SALE_LINES: 'list_sale_lines',
  LIST_DOCUMENT_JOBS: 'list_document_jobs',
  LIST_PRINTABLE_DOCUMENTS: 'list_printable_documents',
  LIST_BUSINESS_DOCUMENTS: 'list_business_documents',
  GET_BUSINESS_DOCUMENT_DETAIL: 'get_business_document_detail',
  GET_BUSINESS_DOCUMENT_REPORTS: 'get_business_document_reports',
  GET_CUSTOMER_DOCUMENT_PAYLOAD: 'get_customer_document_payload',
  GENERATE_CUSTOMER_DOCUMENT_PDF: 'generate_customer_document_pdf',
  ENQUEUE_CUSTOMER_REPRINT: 'enqueue_customer_reprint',
  LIST_JOURNALS: 'list_journals',
  GET_JOURNAL_DETAIL: 'get_journal_detail',
  // Slice 2 — variant catalog
  CREATE_PRODUCT_WITH_VARIANTS: 'create_product_with_variants',
  ADD_VARIANT: 'add_variant',
  UPDATE_VARIANT: 'update_variant',
  SET_VARIANT_ACTIVE: 'set_variant_active',
  UPDATE_PRODUCT: 'update_product',
  CREATE_ATTRIBUTE: 'create_attribute',
  ADD_ATTRIBUTE_VALUE: 'add_attribute_value',
  LIST_ATTRIBUTES: 'list_attributes',
  CREATE_UNIT: 'create_unit',
  LIST_UNITS: 'list_units',
  SET_VARIANT_ATTRIBUTES: 'set_variant_attributes',
  ADD_VARIANT_BARCODE: 'add_variant_barcode',
  REMOVE_VARIANT_BARCODE: 'remove_variant_barcode',
  ADD_VARIANT_ALT_UNIT: 'add_variant_alt_unit',
  REMOVE_VARIANT_ALT_UNIT: 'remove_variant_alt_unit',
  SET_VARIANT_BASE_UNIT: 'set_variant_base_unit',
  RESOLVE_BARCODE: 'resolve_barcode',
  LIST_CATALOG_PRODUCTS: 'list_catalog_products',
  GET_PRODUCT_DETAIL: 'get_product_detail',
  // WS-D-2 — reference-data lifecycle, quick_create_product,
  // list_products_v2, and the widened update_product/update_variant
  // overloads.
  LIST_CATEGORIES: 'list_categories',
  CREATE_CATEGORY: 'create_category',
  RENAME_CATEGORY: 'rename_category',
  SET_CATEGORY_ACTIVE: 'set_category_active',
  DELETE_CATEGORY: 'delete_category',
  LIST_BRANDS: 'list_brands',
  CREATE_BRAND: 'create_brand',
  RENAME_BRAND: 'rename_brand',
  SET_BRAND_ACTIVE: 'set_brand_active',
  DELETE_BRAND: 'delete_brand',
  LIST_ATTRIBUTES_V2: 'list_attributes_v2',
  RENAME_ATTRIBUTE: 'rename_attribute',
  SET_ATTRIBUTE_ACTIVE: 'set_attribute_active',
  DELETE_ATTRIBUTE: 'delete_attribute',
  LIST_ATTRIBUTE_VALUES: 'list_attribute_values',
  RENAME_ATTRIBUTE_VALUE: 'rename_attribute_value',
  SET_ATTRIBUTE_VALUE_ACTIVE: 'set_attribute_value_active',
  DELETE_ATTRIBUTE_VALUE: 'delete_attribute_value',
  LIST_UNITS_V2: 'list_units_v2',
  RENAME_UNIT: 'rename_unit',
  SET_UNIT_ACTIVE: 'set_unit_active',
  DELETE_UNIT: 'delete_unit',
  QUICK_CREATE_PRODUCT: 'quick_create_product',
  LIST_PRODUCTS_V2: 'list_products_v2',
  UPDATE_PRODUCT_V2: 'update_product_v2',
  UPDATE_VARIANT_V2: 'update_variant_v2',
  // Slice 3 — Procurement & Purchase Orders
  CREATE_SUPPLIER: 'create_supplier',
  UPDATE_SUPPLIER: 'update_supplier',
  LIST_SUPPLIERS: 'list_suppliers',
  CREATE_PURCHASE_ORDER_DRAFT: 'create_purchase_order_draft',
  UPDATE_PURCHASE_ORDER_DRAFT: 'update_purchase_order_draft',
  CONFIRM_PURCHASE_ORDER: 'confirm_purchase_order',
  CANCEL_PURCHASE_ORDER: 'cancel_purchase_order',
  LIST_PURCHASE_ORDERS: 'list_purchase_orders',
  GET_PURCHASE_ORDER_DETAIL: 'get_purchase_order_detail',
  CONFIRM_PURCHASE_RECEIPT: 'confirm_purchase_receipt',
  CONFIRM_DIRECT_PURCHASE: 'confirm_direct_purchase',
  LIST_PURCHASE_RECEIPTS: 'list_purchase_receipts',
  LIST_PURCHASE_RECEIPT_LINES: 'list_purchase_receipt_lines',
  GET_PROCUREMENT_CAPABILITIES: 'get_procurement_capabilities',
  ALLOCATE_LANDED_COST: 'allocate_landed_cost',
  CREATE_SUPPLIER_INVOICE_DRAFT: 'create_supplier_invoice_draft',
  CONFIRM_SUPPLIER_INVOICE: 'confirm_supplier_invoice',
  LIST_SUPPLIER_INVOICES: 'list_supplier_invoices',
  LIST_SUPPLIER_LIABILITIES: 'list_supplier_liabilities',
  CREATE_SUPPLIER_RETURN_DRAFT: 'create_supplier_return_draft',
  CONFIRM_SUPPLIER_RETURN: 'confirm_supplier_return',
  POST_SUPPLIER_PAYMENT: 'post_supplier_payment',
  LIST_SUPPLIER_RETURNS: 'list_supplier_returns',
  LIST_SUPPLIER_PAYMENTS: 'list_supplier_payments',
  LIST_PURCHASE_PRODUCT_OPTIONS: 'list_purchase_product_options',
  POST_PURCHASE_TRANSACTION: 'post_purchase_transaction',
  // Slice 4 — Customers & receivables
  CREATE_CUSTOMER: 'create_customer',
  UPDATE_CUSTOMER: 'update_customer',
  LIST_CUSTOMERS: 'list_customers',
  GET_CUSTOMER_CAPABILITIES: 'get_customer_capabilities',
  GET_CUSTOMER_CREDIT_SUMMARY: 'get_customer_credit_summary',
  LIST_CUSTOMER_LEDGER: 'list_customer_ledger',
  LIST_OPEN_CUSTOMER_INVOICES: 'list_open_customer_invoices',
  POST_CUSTOMER_PAYMENT: 'post_customer_payment',
  LIST_REFUNDABLE_CUSTOMER_PAYMENTS: 'list_refundable_customer_payments',
  AUTHORIZE_CUSTOMER_PAYMENT_REFUND: 'authorize_customer_payment_refund',
  POST_CUSTOMER_REFUND: 'post_customer_refund',
  CONFIRM_CREDIT_SALE: 'confirm_credit_sale',
  AUTHORIZE_CREDIT_OVERRIDE: 'authorize_credit_override',
  
  // WS-A-2 / WS-A-3 IAM
  CREATE_USER: 'create_user',
  LIST_USERS: 'list_users',
  SET_USER_ACTIVE: 'set_user_active',
  ASSIGN_USER_ROLE: 'assign_user_role',
  CREATE_ROLE: 'create_role',
  LIST_PERMISSIONS: 'list_permissions',
  LIST_ROLES: 'list_roles',
  LIST_ROLE_PERMISSIONS: 'list_role_permissions',
  SET_ROLE_PERMISSIONS: 'set_role_permissions',
} as const;

export type CommandName = (typeof COMMANDS)[keyof typeof COMMANDS];
