/**
 * Slice 1 — central registry of every production Tauri IPC command name.
 */
export const COMMANDS = {
  GET_APP_INFO: 'get_app_info',
  CHECK_DB_HEALTH: 'check_db_health',
  GET_SETUP_STATUS: 'get_setup_status',
  BOOTSTRAP_FIRST_ADMIN: 'bootstrap_first_admin',
  LOGIN: 'login',
  LOGOUT: 'logout',
  CREATE_PRODUCT: 'create_product',
  LIST_PRODUCTS: 'list_products',
  CREATE_WAREHOUSE: 'create_warehouse',
  LIST_WAREHOUSES: 'list_warehouses',
  LIST_FISCAL_PERIODS: 'list_fiscal_periods',
  GET_OPEN_FISCAL_PERIOD: 'get_open_fiscal_period',
  GET_DASHBOARD_SUMMARY: 'get_dashboard_summary',
  POST_STOCK_RECEIPT: 'post_stock_receipt',
  CONFIRM_STOCK_ADJUSTMENT: 'confirm_stock_adjustment',
  LIST_STOCK_ADJUSTMENT_UNITS: 'list_stock_adjustment_units',
  OPEN_CASH_SESSION: 'open_cash_session',
  INSPECT_ACTIVE_CASH_SESSION: 'inspect_active_cash_session',
  CLOSE_CASH_SESSION: 'close_cash_session',
  GET_CASH_SESSION: 'get_cash_session',
  CONFIRM_CASH_SALE: 'confirm_cash_sale',
  GET_SALE_DOCUMENT: 'get_sale_document',
  LIST_SALE_LINES: 'list_sale_lines',
  LIST_DOCUMENT_JOBS: 'list_document_jobs',
  // Slice 2 — variant catalog
  CREATE_PRODUCT_WITH_VARIANTS: 'create_product_with_variants',
  ADD_VARIANT: 'add_variant',
  UPDATE_VARIANT: 'update_variant',
  SET_VARIANT_ACTIVE: 'set_variant_active',
  UPDATE_PRODUCT: 'update_product',
  CREATE_ATTRIBUTE: 'create_attribute',
  ADD_ATTRIBUTE_VALUE: 'add_attribute_value',
  LIST_ATTRIBUTES: 'list_attributes',
  CREATE_UNIT: 'create_unit',
  LIST_UNITS: 'list_units',
  SET_VARIANT_ATTRIBUTES: 'set_variant_attributes',
  ADD_VARIANT_BARCODE: 'add_variant_barcode',
  REMOVE_VARIANT_BARCODE: 'remove_variant_barcode',
  ADD_VARIANT_ALT_UNIT: 'add_variant_alt_unit',
  REMOVE_VARIANT_ALT_UNIT: 'remove_variant_alt_unit',
  SET_VARIANT_BASE_UNIT: 'set_variant_base_unit',
  RESOLVE_BARCODE: 'resolve_barcode',
  LIST_CATALOG_PRODUCTS: 'list_catalog_products',
  GET_PRODUCT_DETAIL: 'get_product_detail',
  // Slice 3 — Procurement & Purchase Orders
  CREATE_SUPPLIER: 'create_supplier',
  UPDATE_SUPPLIER: 'update_supplier',
  LIST_SUPPLIERS: 'list_suppliers',
  CREATE_PURCHASE_ORDER_DRAFT: 'create_purchase_order_draft',
  UPDATE_PURCHASE_ORDER_DRAFT: 'update_purchase_order_draft',
  CONFIRM_PURCHASE_ORDER: 'confirm_purchase_order',
  CANCEL_PURCHASE_ORDER: 'cancel_purchase_order',
  LIST_PURCHASE_ORDERS: 'list_purchase_orders',
  GET_PURCHASE_ORDER_DETAIL: 'get_purchase_order_detail',
  CONFIRM_PURCHASE_RECEIPT: 'confirm_purchase_receipt',
  LIST_PURCHASE_RECEIPTS: 'list_purchase_receipts',
  ALLOCATE_LANDED_COST: 'allocate_landed_cost',
  CREATE_SUPPLIER_INVOICE_DRAFT: 'create_supplier_invoice_draft',
  CONFIRM_SUPPLIER_INVOICE: 'confirm_supplier_invoice',
  LIST_SUPPLIER_INVOICES: 'list_supplier_invoices',
  LIST_SUPPLIER_LIABILITIES: 'list_supplier_liabilities',
  CREATE_SUPPLIER_RETURN_DRAFT: 'create_supplier_return_draft',
  CONFIRM_SUPPLIER_RETURN: 'confirm_supplier_return',
  POST_SUPPLIER_PAYMENT: 'post_supplier_payment',
  LIST_SUPPLIER_RETURNS: 'list_supplier_returns',
  LIST_SUPPLIER_PAYMENTS: 'list_supplier_payments',
  CREATE_CUSTOMER: 'create_customer',
  LIST_CUSTOMERS: 'list_customers',
  LIST_CUSTOMER_LIABILITIES: 'list_customer_liabilities',
  LIST_CUSTOMER_PAYMENTS: 'list_customer_payments',
  POST_CUSTOMER_PAYMENT: 'post_customer_payment',
  SUSPEND_CASH_SESSION: 'suspend_cash_session',
  RESUME_CASH_SESSION: 'resume_cash_session',
  SUBMIT_SESSION_CLOSING: 'submit_session_closing',
  APPROVE_CASH_VARIANCE: 'approve_session_variance',
  LIST_PENDING_VARIANCE_SESSIONS: 'list_pending_variance_sessions',
  GENERATE_CREDIT_OVERRIDE_TOKEN: 'generate_credit_override_token',
} as const;

export type CommandName = (typeof COMMANDS)[keyof typeof COMMANDS];

