// WS-I-1 §5.10 — every label used by report UI, in all three languages.
// Later sub-plans append to this dictionary; they never replace it.

import { useI18n, type Locale } from '../../../shared/i18n';

export const REPORT_COPY: Record<Locale, Record<string, string>> = {
  en: {
    reports: 'Reports',
    tabSales: 'Sales',
    salesSummary: 'Sales summary',
    salesOverTime: 'Sales over time',
    salesByProduct: 'Sales by product',
    bestSellers: 'Best sellers',
    salesByCategory: 'Sales by category',
    salesByCashier: 'Sales by cashier',
    busyHours: 'Busy hours',
    marginAlerts: 'Margin alerts',
    netSales: 'Net sales',
    grossProfit: 'Gross profit',
    marginPct: 'Margin %',
    saleCount: 'Number of sales',
    avgBasket: 'Average basket',
    cashSales: 'Cash sales',
    creditSales: 'Credit sales',
    cancellations: 'Cancellations',
    suggestedMinPrice: 'Suggested minimum price',
    bestSellersNote: 'The best-selling product is not always the most profitable.',
    empty: 'No data for this period.',
    noData: 'No data',
    invalidRange: 'The start date is after the end date.',
    periodText: 'from {from} to {to}',
    exportCapped: 'Only the first 20,000 rows were exported.',
    print: 'Print',
    pdf: 'Save as PDF',
    csv: 'Export CSV',
    retry: 'Retry',
    noCategory: 'No category',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This week',
    lastWeek: 'Last week',
    thisMonth: 'This month',
    lastMonth: 'Last month',
    thisYear: 'This year',
    custom: 'Custom',
    weekdaySat: 'Saturday',
    weekdaySun: 'Sunday',
    weekdayMon: 'Monday',
    weekdayTue: 'Tuesday',
    weekdayWed: 'Wednesday',
    weekdayThu: 'Thursday',
    weekdayFri: 'Friday',
  },
  fr: {
    reports: 'Rapports',
    tabSales: 'Ventes',
    salesSummary: 'Synthèse des ventes',
    salesOverTime: 'Évolution des ventes',
    salesByProduct: 'Ventes par produit',
    bestSellers: 'Meilleures ventes',
    salesByCategory: 'Ventes par catégorie',
    salesByCashier: 'Ventes par caissier',
    busyHours: 'Heures d’affluence',
    marginAlerts: 'Alertes de marge',
    netSales: 'Ventes nettes',
    grossProfit: 'Marge brute',
    marginPct: 'Taux de marge',
    saleCount: 'Nombre de ventes',
    avgBasket: 'Panier moyen',
    cashSales: 'Ventes au comptant',
    creditSales: 'Ventes à crédit',
    cancellations: 'Annulations',
    suggestedMinPrice: 'Prix minimum conseillé',
    bestSellersNote: 'Le produit le plus vendu n’est pas toujours le plus rentable.',
    empty: 'Aucune donnée pour cette période.',
    noData: 'Aucune donnée',
    invalidRange: 'La date de début est après la date de fin.',
    periodText: 'du {from} au {to}',
    exportCapped: 'Seules les 20 000 premières lignes ont été exportées.',
    print: 'Imprimer',
    pdf: 'Enregistrer en PDF',
    csv: 'Exporter en CSV',
    retry: 'Réessayer',
    noCategory: 'Sans catégorie',
    today: 'Aujourd’hui',
    yesterday: 'Hier',
    thisWeek: 'Cette semaine',
    lastWeek: 'Semaine dernière',
    thisMonth: 'Ce mois',
    lastMonth: 'Mois dernier',
    thisYear: 'Cette année',
    custom: 'Personnalisé',
    weekdaySat: 'Samedi',
    weekdaySun: 'Dimanche',
    weekdayMon: 'Lundi',
    weekdayTue: 'Mardi',
    weekdayWed: 'Mercredi',
    weekdayThu: 'Jeudi',
    weekdayFri: 'Vendredi',
  },
  ar: {
    reports: 'التقارير',
    tabSales: 'المبيعات',
    salesSummary: 'ملخص المبيعات',
    salesOverTime: 'تطور المبيعات',
    salesByProduct: 'المبيعات حسب المنتج',
    bestSellers: 'الأكثر مبيعًا',
    salesByCategory: 'المبيعات حسب الفئة',
    salesByCashier: 'المبيعات حسب أمين الصندوق',
    busyHours: 'أوقات الذروة',
    marginAlerts: 'تنبيهات الهامش',
    netSales: 'صافي المبيعات',
    grossProfit: 'الربح الإجمالي',
    marginPct: 'نسبة الهامش',
    saleCount: 'عدد المبيعات',
    avgBasket: 'متوسط السلة',
    cashSales: 'المبيعات النقدية',
    creditSales: 'المبيعات بالآجل',
    cancellations: 'الإلغاءات',
    suggestedMinPrice: 'أدنى سعر مقترح',
    bestSellersNote: 'المنتج الأكثر مبيعًا ليس دائمًا الأكثر ربحًا.',
    empty: 'لا توجد بيانات لهذه الفترة.',
    noData: 'لا توجد بيانات',
    invalidRange: 'تاريخ البداية بعد تاريخ النهاية.',
    periodText: 'من {from} إلى {to}',
    exportCapped: 'تم تصدير أول 20000 سطر فقط.',
    print: 'طباعة',
    pdf: 'حفظ PDF',
    csv: 'تصدير CSV',
    retry: 'إعادة المحاولة',
    noCategory: 'بدون فئة',
    today: 'اليوم',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    lastWeek: 'الأسبوع الماضي',
    thisMonth: 'هذا الشهر',
    lastMonth: 'الشهر الماضي',
    thisYear: 'هذه السنة',
    custom: 'مخصص',
    weekdaySat: 'السبت',
    weekdaySun: 'الأحد',
    weekdayMon: 'الاثنين',
    weekdayTue: 'الثلاثاء',
    weekdayWed: 'الأربعاء',
    weekdayThu: 'الخميس',
    weekdayFri: 'الجمعة',
  },
};

/** 0 = Saturday … 6 = Friday (A5). */
export const WEEKDAY_KEYS = [
  'weekdaySat',
  'weekdaySun',
  'weekdayMon',
  'weekdayTue',
  'weekdayWed',
  'weekdayThu',
  'weekdayFri',
] as const;

export function useReportCopy(): Record<string, string> {
  const { locale } = useI18n();
  return REPORT_COPY[locale];
}

export function formatReportCopy(template: string, vars: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => vars[key] ?? match);
}
