// WS-I-1 §5.10 — every label used by report UI, in all three languages.
// Later sub-plans append to this dictionary; they never replace it.

import { useI18n, type Locale } from '../../../shared/i18n';

export const REPORT_COPY: Record<Locale, Record<string, string>> = {
  en: {
    reports: 'Reports',
    tabSales: 'Sales',
    salesSummary: 'Sales summary',
    salesOverTime: 'Sales over time',
    salesByProduct: 'Sales by product',
    bestSellers: 'Best sellers',
    salesByCategory: 'Sales by category',
    salesByCashier: 'Sales by cashier',
    busyHours: 'Busy hours',
    marginAlerts: 'Margin alerts',
    netSales: 'Net sales',
    grossProfit: 'Gross profit',
    marginPct: 'Margin %',
    saleCount: 'Number of sales',
    avgBasket: 'Average basket',
    cashSales: 'Cash sales',
    creditSales: 'Credit sales',
    cancellations: 'Cancellations',
    suggestedMinPrice: 'Suggested minimum price',
    bestSellersNote: 'The best-selling product is not always the most profitable.',
    empty: 'No data for this period.',
    noData: 'No data',
    invalidRange: 'The start date is after the end date.',
    periodText: 'from {from} to {to}',
    periodLabel: 'Period',
    periodFrom: 'From',
    periodTo: 'To',
    exportCapped: 'Only the first 20,000 rows were exported.',
    print: 'Print',
    pdf: 'Save as PDF',
    csv: 'Export CSV',
    retry: 'Retry',
    noCategory: 'No category',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This week',
    lastWeek: 'Last week',
    thisMonth: 'This month',
    lastMonth: 'Last month',
    thisYear: 'This year',
    custom: 'Custom',
    weekdaySat: 'Saturday',
    weekdaySun: 'Sunday',
    weekdayMon: 'Monday',
    weekdayTue: 'Tuesday',
    weekdayWed: 'Wednesday',
    weekdayThu: 'Thursday',
    weekdayFri: 'Friday',
    // WS-I-2
    tabFinance: 'Finance',
    tabOwed: 'Money owed',
    tabAccounting: 'Accounting',
    monthlySummary: 'Monthly summary',
    profitLoss: 'Profit & loss',
    cashFlow: 'Cash flow',
    receivables: 'Customers who owe',
    customerStatement: 'Customer statement',
    suppliersBalances: 'Suppliers',
    supplierStatement: 'Supplier statement',
    trialBalance: 'Trial balance',
    accountLedger: 'Account ledger',
    costOfSales: 'Cost of sales',
    expenses: 'Expenses',
    cashShortages: 'Cash shortages',
    cashOverages: 'Cash overages',
    netResult: 'Net result',
    otherCashOutNote:
      'Not counted as an expense. Classify these cash-outs as "Expense" when they are business costs.',
    managementViewNote:
      'Management view based on sales and cash records. The accounting view is in the Accounting tab.',
    owedToYou: 'Owed to you',
    youOwe: 'You owe suppliers',
    stockValue: 'Stock value',
    purchases: 'Purchases',
    notDue: 'Not due',
    daysOverdue: 'Days overdue',
    copyReminder: 'Copy reminder',
    copied: 'Copied',
    openingBalance: 'Opening balance',
    closingBalance: 'Closing balance',
    balanceDue: 'Balance due',
    balanced: 'Balanced',
    notBalanced: 'Not balanced — difference {x}',
    entryTypeCreditInvoice: 'Credit sale',
    entryTypePayment: 'Payment',
    entryTypePaymentRefund: 'Payment refunded',
    entryTypeCreditNote: 'Credit note (sale cancelled)',
    entryTypeDebitNote: 'Debit note',
    entryTypeWriteOff: 'Write-off',
    entryTypeAdjustment: 'Adjustment',
    entryTypePurchaseReceipt: 'Purchase',
    entryTypePurchaseReturn: 'Return to supplier',
    entryTypeSupplierPayment: 'Payment to supplier',
    // WS-I-3
    tabStock: 'Stock',
    stockValuation: 'Valuation',
    lowStock: 'Low stock',
    slowMovers: 'Slow movers',
    productHistory: 'Product history',
    category: 'Category',
    allCategories: 'All categories',
    search: 'Search',
    avgCost: 'Avg cost',
    salePrice: 'Sale price',
    retailValue: 'Retail value',
    potentialMargin: 'Potential margin',
    onHand: 'On hand',
    minimumStock: 'Minimum',
    suggestedOrder: 'Suggested order',
    lastSupplier: 'Last supplier',
    lastCost: 'Last cost',
    lastPurchase: 'Last purchase',
    preparePurchase: 'Prepare purchase',
    selectAllOnPage: 'Select all on this page',
    prepareSupplierDialogTitle: 'Choose a supplier for this purchase',
    chooseLater: 'Choose later',
    slowDays30: '30 days',
    slowDays60: '60 days',
    slowDays90: '90 days',
    slowDays180: '180 days',
    slowMoversBanner: '{count} products · {value} DA tied up in stock',
    lastSale: 'Last sale',
    neverSold: 'Never sold',
    daysSince: 'Days since',
    productHistorySearch: 'Search for a product',
    dateTime: 'Date & time',
    movement: 'Movement',
    document: 'Document',
    quantityChange: 'Quantity change',
    runningQuantity: 'Running quantity',
    openingQuantity: 'Opening quantity',
    closingQuantity: 'Closing quantity',
    prefillBanner: '{n} lines were prepared from the low-stock report. Review them before saving.',
    prefillSkipped: '{m} lines were skipped because the product is no longer available.',
    // Notifications
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    notifGoTo: 'View',
    dismissToday: 'Dismiss for today',
    notifOutOfStockTitle: 'Out of stock',
    notifOutOfStockDetail: '{count} products',
    notifLowStockTitle: 'Low stock',
    notifLowStockDetail: '{count} products',
    notifOverdueDebtsTitle: 'Overdue customer debts',
    notifOverdueDebtsDetail: '{count} customers · {amount} DA',
    notifCreditLimitTitle: 'Credit limit exceeded',
    notifCreditLimitDetail: '{count} customers',
    notifMarginAlertsTitle: 'Sold below cost (7 days)',
    notifMarginAlertsDetail: '{count} products',
    notifSlowMoversTitle: 'Slow movers',
    notifSlowMoversDetail: '{count} products · {amount} DA tied up',
    notifCashSessionTitle: 'Cash session open too long',
    notifCashSessionDetail: '{hours} h',
    notifBackupTitle: 'No recent backup',
    notifBackupDetailDate: 'Last: {date}',
    notifBackupDetailNever: 'Never',
    // Today home
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    homeNoReports: 'Sales figures are available to managers and administrators.',
    kpiSales: 'Net sales',
    kpiProfit: 'Gross profit',
    kpiCount: 'Number of sales',
    kpiBasket: 'Average basket',
    kpiDrawer: 'Cash expected',
    noSessionOpen: 'No session open',
    openSession: 'Open session',
    hourlySalesToday: "Today's sales by hour",
    topProductsToday: 'Top products today',
    owedToYouHome: 'Owed to you',
    youOweHome: 'You owe suppliers',
    lowStockHome: 'Low stock',
    monthToDate: 'Month to date',
    copyDailySummary: "Copy today's summary for WhatsApp",
    systemStatus: 'System status',
  },
  fr: {
    reports: 'Rapports',
    tabSales: 'Ventes',
    salesSummary: 'Synthèse des ventes',
    salesOverTime: 'Évolution des ventes',
    salesByProduct: 'Ventes par produit',
    bestSellers: 'Meilleures ventes',
    salesByCategory: 'Ventes par catégorie',
    salesByCashier: 'Ventes par caissier',
    busyHours: 'Heures d’affluence',
    marginAlerts: 'Alertes de marge',
    netSales: 'Ventes nettes',
    grossProfit: 'Marge brute',
    marginPct: 'Taux de marge',
    saleCount: 'Nombre de ventes',
    avgBasket: 'Panier moyen',
    cashSales: 'Ventes au comptant',
    creditSales: 'Ventes à crédit',
    cancellations: 'Annulations',
    suggestedMinPrice: 'Prix minimum conseillé',
    bestSellersNote: 'Le produit le plus vendu n’est pas toujours le plus rentable.',
    empty: 'Aucune donnée pour cette période.',
    noData: 'Aucune donnée',
    invalidRange: 'La date de début est après la date de fin.',
    periodText: 'du {from} au {to}',
    periodLabel: 'Période',
    periodFrom: 'Du',
    periodTo: 'Au',
    exportCapped: 'Seules les 20 000 premières lignes ont été exportées.',
    print: 'Imprimer',
    pdf: 'Enregistrer en PDF',
    csv: 'Exporter en CSV',
    retry: 'Réessayer',
    noCategory: 'Sans catégorie',
    today: 'Aujourd’hui',
    yesterday: 'Hier',
    thisWeek: 'Cette semaine',
    lastWeek: 'Semaine dernière',
    thisMonth: 'Ce mois',
    lastMonth: 'Mois dernier',
    thisYear: 'Cette année',
    custom: 'Personnalisé',
    weekdaySat: 'Samedi',
    weekdaySun: 'Dimanche',
    weekdayMon: 'Lundi',
    weekdayTue: 'Mardi',
    weekdayWed: 'Mercredi',
    weekdayThu: 'Jeudi',
    weekdayFri: 'Vendredi',
    // WS-I-2
    tabFinance: 'Finance',
    tabOwed: 'Créances et dettes',
    tabAccounting: 'Comptabilité',
    monthlySummary: 'Synthèse mensuelle',
    profitLoss: 'Compte de résultat',
    cashFlow: 'Flux de trésorerie',
    receivables: 'Créances clients',
    customerStatement: 'Relevé client',
    suppliersBalances: 'Fournisseurs',
    supplierStatement: 'Relevé fournisseur',
    trialBalance: 'Balance générale',
    accountLedger: 'Grand livre',
    costOfSales: 'Coût des ventes',
    expenses: 'Charges',
    cashShortages: 'Manquants de caisse',
    cashOverages: 'Excédents de caisse',
    netResult: 'Résultat net',
    otherCashOutNote:
      'Non compté en charges. Classez ces sorties en « Dépense » lorsqu’il s’agit de frais de l’activité.',
    managementViewNote:
      'Vue de gestion basée sur les ventes et la caisse. La vue comptable se trouve dans l’onglet Comptabilité.',
    owedToYou: 'On vous doit',
    youOwe: 'Vous devez aux fournisseurs',
    stockValue: 'Valeur du stock',
    purchases: 'Achats',
    notDue: 'Non échu',
    daysOverdue: 'Jours de retard',
    copyReminder: 'Copier le rappel',
    copied: 'Copié',
    openingBalance: 'Solde initial',
    closingBalance: 'Solde final',
    balanceDue: 'Solde dû',
    balanced: 'Équilibrée',
    notBalanced: 'Non équilibrée — écart {x}',
    entryTypeCreditInvoice: 'Vente à crédit',
    entryTypePayment: 'Règlement',
    entryTypePaymentRefund: 'Remboursement de règlement',
    entryTypeCreditNote: 'Avoir (vente annulée)',
    entryTypeDebitNote: 'Note de débit',
    entryTypeWriteOff: 'Passage en perte',
    entryTypeAdjustment: 'Ajustement',
    entryTypePurchaseReceipt: 'Achat',
    entryTypePurchaseReturn: 'Retour fournisseur',
    entryTypeSupplierPayment: 'Paiement fournisseur',
    // WS-I-3
    tabStock: 'Stock',
    stockValuation: 'Valorisation',
    lowStock: 'Stock bas',
    slowMovers: 'Produits dormants',
    productHistory: 'Historique produit',
    category: 'Catégorie',
    allCategories: 'Toutes les catégories',
    search: 'Rechercher',
    avgCost: 'Coût moyen',
    salePrice: 'Prix de vente',
    retailValue: 'Valeur de vente',
    potentialMargin: 'Marge potentielle',
    onHand: 'En stock',
    minimumStock: 'Minimum',
    suggestedOrder: 'Quantité suggérée',
    lastSupplier: 'Dernier fournisseur',
    lastCost: 'Dernier coût',
    lastPurchase: 'Dernier achat',
    preparePurchase: 'Préparer un achat',
    selectAllOnPage: 'Tout sélectionner sur cette page',
    prepareSupplierDialogTitle: 'Choisissez un fournisseur pour cet achat',
    chooseLater: 'Choisir plus tard',
    slowDays30: '30 jours',
    slowDays60: '60 jours',
    slowDays90: '90 jours',
    slowDays180: '180 jours',
    slowMoversBanner: '{count} produits · {value} DA immobilisés en stock',
    lastSale: 'Dernière vente',
    neverSold: 'Jamais vendu',
    daysSince: 'Jours écoulés',
    productHistorySearch: 'Rechercher un produit',
    dateTime: 'Date et heure',
    movement: 'Mouvement',
    document: 'Document',
    quantityChange: 'Variation de quantité',
    runningQuantity: 'Quantité cumulée',
    openingQuantity: "Quantité d'ouverture",
    closingQuantity: 'Quantité de clôture',
    prefillBanner: "{n} lignes ont été préparées depuis le rapport de stock bas. Vérifiez-les avant d'enregistrer.",
    prefillSkipped: "{m} lignes ont été ignorées car le produit n'est plus disponible.",
    // Notifications
    notifications: 'Notifications',
    noNotifications: 'Aucune notification',
    notifGoTo: 'Voir',
    dismissToday: "Ignorer pour aujourd'hui",
    notifOutOfStockTitle: 'Rupture de stock',
    notifOutOfStockDetail: '{count} produits',
    notifLowStockTitle: 'Stock bas',
    notifLowStockDetail: '{count} produits',
    notifOverdueDebtsTitle: 'Créances échues',
    notifOverdueDebtsDetail: '{count} clients · {amount} DA',
    notifCreditLimitTitle: 'Plafond de crédit dépassé',
    notifCreditLimitDetail: '{count} clients',
    notifMarginAlertsTitle: 'Vendu à perte (7 jours)',
    notifMarginAlertsDetail: '{count} produits',
    notifSlowMoversTitle: 'Produits dormants',
    notifSlowMoversDetail: '{count} produits · {amount} DA immobilisés',
    notifCashSessionTitle: 'Session de caisse ouverte trop longtemps',
    notifCashSessionDetail: '{hours} h',
    notifBackupTitle: 'Pas de sauvegarde récente',
    notifBackupDetailDate: 'Dernière : {date}',
    notifBackupDetailNever: 'Jamais',
    // Today home
    greetingMorning: 'Bonjour',
    greetingAfternoon: 'Bon après-midi',
    greetingEvening: 'Bonsoir',
    homeNoReports: 'Les chiffres de vente sont réservés aux responsables et administrateurs.',
    kpiSales: 'Ventes nettes',
    kpiProfit: 'Marge brute',
    kpiCount: 'Nombre de ventes',
    kpiBasket: 'Panier moyen',
    kpiDrawer: 'Caisse attendue',
    noSessionOpen: 'Aucune session ouverte',
    openSession: 'Ouvrir une session',
    hourlySalesToday: "Ventes du jour par heure",
    topProductsToday: "Meilleures ventes du jour",
    owedToYouHome: 'On vous doit',
    youOweHome: 'Vous devez aux fournisseurs',
    lowStockHome: 'Stock bas',
    monthToDate: 'Depuis le début du mois',
    copyDailySummary: "Copier le résumé du jour pour WhatsApp",
    systemStatus: 'État du système',
  },
  ar: {
    reports: 'التقارير',
    tabSales: 'المبيعات',
    salesSummary: 'ملخص المبيعات',
    salesOverTime: 'تطور المبيعات',
    salesByProduct: 'المبيعات حسب المنتج',
    bestSellers: 'الأكثر مبيعًا',
    salesByCategory: 'المبيعات حسب الفئة',
    salesByCashier: 'المبيعات حسب أمين الصندوق',
    busyHours: 'أوقات الذروة',
    marginAlerts: 'تنبيهات الهامش',
    netSales: 'صافي المبيعات',
    grossProfit: 'الربح الإجمالي',
    marginPct: 'نسبة الهامش',
    saleCount: 'عدد المبيعات',
    avgBasket: 'متوسط السلة',
    cashSales: 'المبيعات النقدية',
    creditSales: 'المبيعات بالآجل',
    cancellations: 'الإلغاءات',
    suggestedMinPrice: 'أدنى سعر مقترح',
    bestSellersNote: 'المنتج الأكثر مبيعًا ليس دائمًا الأكثر ربحًا.',
    empty: 'لا توجد بيانات لهذه الفترة.',
    noData: 'لا توجد بيانات',
    invalidRange: 'تاريخ البداية بعد تاريخ النهاية.',
    periodText: 'من {from} إلى {to}',
    periodLabel: 'الفترة',
    periodFrom: 'من',
    periodTo: 'إلى',
    exportCapped: 'تم تصدير أول 20000 سطر فقط.',
    print: 'طباعة',
    pdf: 'حفظ PDF',
    csv: 'تصدير CSV',
    retry: 'إعادة المحاولة',
    noCategory: 'بدون فئة',
    today: 'اليوم',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    lastWeek: 'الأسبوع الماضي',
    thisMonth: 'هذا الشهر',
    lastMonth: 'الشهر الماضي',
    thisYear: 'هذه السنة',
    custom: 'مخصص',
    weekdaySat: 'السبت',
    weekdaySun: 'الأحد',
    weekdayMon: 'الاثنين',
    weekdayTue: 'الثلاثاء',
    weekdayWed: 'الأربعاء',
    weekdayThu: 'الخميس',
    weekdayFri: 'الجمعة',
    // WS-I-2
    tabFinance: 'المالية',
    tabOwed: 'الديون',
    tabAccounting: 'المحاسبة',
    monthlySummary: 'الملخص الشهري',
    profitLoss: 'حساب النتائج',
    cashFlow: 'التدفقات النقدية',
    receivables: 'ديون العملاء',
    customerStatement: 'كشف حساب العميل',
    suppliersBalances: 'الموردون',
    supplierStatement: 'كشف حساب المورّد',
    trialBalance: 'ميزان المراجعة',
    accountLedger: 'دفتر الأستاذ',
    costOfSales: 'تكلفة المبيعات',
    expenses: 'المصاريف',
    cashShortages: 'عجز الصندوق',
    cashOverages: 'فائض الصندوق',
    netResult: 'النتيجة الصافية',
    otherCashOutNote: 'غير محسوب ضمن المصاريف. صنّف هذه المخرجات كـ«مصروف» إذا كانت من تكاليف النشاط.',
    managementViewNote: 'عرض تسييري مبني على المبيعات والصندوق. العرض المحاسبي موجود في تبويب المحاسبة.',
    owedToYou: 'ديون لكم',
    youOwe: 'ديون عليكم للموردين',
    stockValue: 'قيمة المخزون',
    purchases: 'المشتريات',
    notDue: 'غير مستحق',
    daysOverdue: 'أيام التأخير',
    copyReminder: 'نسخ التذكير',
    copied: 'تم النسخ',
    openingBalance: 'الرصيد الافتتاحي',
    closingBalance: 'الرصيد الختامي',
    balanceDue: 'الرصيد المستحق',
    balanced: 'متوازن',
    notBalanced: 'غير متوازن — الفرق {x}',
    entryTypeCreditInvoice: 'بيع بالآجل',
    entryTypePayment: 'دفعة',
    entryTypePaymentRefund: 'استرداد دفعة',
    entryTypeCreditNote: 'إشعار دائن (بيع ملغى)',
    entryTypeDebitNote: 'إشعار مدين',
    entryTypeWriteOff: 'شطب',
    entryTypeAdjustment: 'تسوية',
    entryTypePurchaseReceipt: 'شراء',
    entryTypePurchaseReturn: 'إرجاع للمورّد',
    entryTypeSupplierPayment: 'دفعة للمورّد',
    // WS-I-3
    tabStock: 'المخزون',
    stockValuation: 'تقييم المخزون',
    lowStock: 'مخزون منخفض',
    slowMovers: 'منتجات راكدة',
    productHistory: 'سجل المنتج',
    category: 'الفئة',
    allCategories: 'كل الفئات',
    search: 'بحث',
    avgCost: 'متوسط التكلفة',
    salePrice: 'سعر البيع',
    retailValue: 'قيمة البيع',
    potentialMargin: 'الهامش المحتمل',
    onHand: 'الكمية المتوفرة',
    minimumStock: 'الحد الأدنى',
    suggestedOrder: 'الكمية المقترحة',
    lastSupplier: 'آخر مورّد',
    lastCost: 'آخر تكلفة',
    lastPurchase: 'آخر شراء',
    preparePurchase: 'تجهيز طلب شراء',
    selectAllOnPage: 'تحديد الكل في هذه الصفحة',
    prepareSupplierDialogTitle: 'اختر موردًا لهذا الشراء',
    chooseLater: 'اختيار لاحقًا',
    slowDays30: '30 يومًا',
    slowDays60: '60 يومًا',
    slowDays90: '90 يومًا',
    slowDays180: '180 يومًا',
    slowMoversBanner: '{count} منتجات · {value} دج مجمّدة في المخزون',
    lastSale: 'آخر بيع',
    neverSold: 'لم يُباع أبدًا',
    daysSince: 'الأيام المنقضية',
    productHistorySearch: 'ابحث عن منتج',
    dateTime: 'التاريخ والوقت',
    movement: 'الحركة',
    document: 'المستند',
    quantityChange: 'تغيّر الكمية',
    runningQuantity: 'الكمية التراكمية',
    openingQuantity: 'الكمية الافتتاحية',
    closingQuantity: 'الكمية الختامية',
    prefillBanner: 'تم تجهيز {n} أسطر من تقرير المخزون المنخفض. راجعها قبل الحفظ.',
    prefillSkipped: 'تم تجاهل {m} أسطر لأن المنتج لم يعد متوفرًا.',
    // Notifications
    notifications: 'الإشعارات',
    noNotifications: 'لا توجد إشعارات',
    notifGoTo: 'عرض',
    dismissToday: 'تجاهل لهذا اليوم',
    notifOutOfStockTitle: 'نفاد المخزون',
    notifOutOfStockDetail: '{count} منتجات',
    notifLowStockTitle: 'مخزون منخفض',
    notifLowStockDetail: '{count} منتجات',
    notifOverdueDebtsTitle: 'ديون عملاء متأخرة',
    notifOverdueDebtsDetail: '{count} عملاء · {amount} دج',
    notifCreditLimitTitle: 'تجاوز سقف الائتمان',
    notifCreditLimitDetail: '{count} عملاء',
    notifMarginAlertsTitle: 'بيع بخسارة (7 أيام)',
    notifMarginAlertsDetail: '{count} منتجات',
    notifSlowMoversTitle: 'منتجات راكدة',
    notifSlowMoversDetail: '{count} منتجات · {amount} دج مجمّدة',
    notifCashSessionTitle: 'حصة الصندوق مفتوحة لمدة طويلة',
    notifCashSessionDetail: '{hours} س',
    notifBackupTitle: 'لا توجد نسخة احتياطية حديثة',
    notifBackupDetailDate: 'آخر نسخة: {date}',
    notifBackupDetailNever: 'أبدًا',
    // Today home
    greetingMorning: 'صباح الخير',
    greetingAfternoon: 'مساء الخير',
    greetingEvening: 'مساء الخير',
    homeNoReports: 'أرقام المبيعات متاحة للمديرين والمسؤولين فقط.',
    kpiSales: 'المبيعات الصافية',
    kpiProfit: 'الربح الإجمالي',
    kpiCount: 'عدد المبيعات',
    kpiBasket: 'متوسط السلة',
    kpiDrawer: 'النقد المتوقع',
    noSessionOpen: 'لا توجد حصة مفتوحة',
    openSession: 'فتح حصة',
    hourlySalesToday: 'مبيعات اليوم حسب الساعة',
    topProductsToday: 'أفضل المنتجات اليوم',
    owedToYouHome: 'مستحق لك',
    youOweHome: 'مستحق على الموردين',
    lowStockHome: 'مخزون منخفض',
    monthToDate: 'منذ بداية الشهر',
    copyDailySummary: 'نسخ ملخص اليوم لواتساب',
    systemStatus: 'حالة النظام',
  },
};

/** 0 = Saturday … 6 = Friday (A5). */
export const WEEKDAY_KEYS = [
  'weekdaySat',
  'weekdaySun',
  'weekdayMon',
  'weekdayTue',
  'weekdayWed',
  'weekdayThu',
  'weekdayFri',
] as const;

export function useReportCopy(): Record<string, string> {
  const { locale } = useI18n();
  return REPORT_COPY[locale];
}

export function formatReportCopy(template: string, vars: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => vars[key] ?? match);
}

const ENTRY_TYPE_KEYS: Record<string, string> = {
  CREDIT_INVOICE: 'entryTypeCreditInvoice',
  PAYMENT: 'entryTypePayment',
  PAYMENT_REFUND: 'entryTypePaymentRefund',
  CREDIT_NOTE: 'entryTypeCreditNote',
  DEBIT_NOTE: 'entryTypeDebitNote',
  WRITE_OFF: 'entryTypeWriteOff',
  ADJUSTMENT: 'entryTypeAdjustment',
  PURCHASE_RECEIPT: 'entryTypePurchaseReceipt',
  PURCHASE_RETURN: 'entryTypePurchaseReturn',
  SUPPLIER_PAYMENT: 'entryTypeSupplierPayment',
};

/** Translates a ledger `entry_type` code (plan §6.1 table); unknown codes show their raw code. */
export function entryTypeLabel(entryType: string, copy: Record<string, string>): string {
  const key = ENTRY_TYPE_KEYS[entryType];
  return key ? copy[key] : entryType;
}
