/**
 * WS-D-11 — the detail column: everything about ONE selected variant (R4, R6).
 *
 * This replaces the expand-in-place accordion. Before, every expanded variant
 * stacked name + identifier + status + actions + figures + attribute picker +
 * barcode section vertically inside a 560px column, several at a time, with the
 * product fields permanently above them. One variant at a time, in its own
 * column, with the product fields moved to their own tab, is the whole fix.
 *
 * R13 — the SKU is shown, visibly non-editable, with click-to-copy. It is
 * generated by `catalog._generate_sku` and must never become an input.
 * R12 — barcodes sit behind a toggle showing their count, closed by default.
 *
 * CR2 — the attribute section renders `AttributeManagerForVariant`, the
 * component that owns the `mergeAssignedValues` wiring. A retired value the
 * variant already holds keeps rendering, stays selectable and stays marked.
 * Writing a picker here instead would reintroduce that data-loss defect.
 */
import { useCallback, useState } from 'react';

import { Banner, Button } from '../../shared/components';
import { useI18n } from '../../shared/i18n';
import type { AttributeDefinition, VariantDetail } from '../../shared/ipc/dto';
import { AttributeManagerForVariant } from '../products/ProductEditor';
import { PanelField } from './PanelFields';
import { useDecimalFormat } from './useDecimalFormat';

export function VariantEditor({
  variant,
  attributes,
  refLoading,
  stock,
  onCommitName,
  onSetAttributes,
  onCreateAttribute,
  onAddValue,
  barcodes,
}: {
  variant: VariantDetail;
  attributes: AttributeDefinition[];
  refLoading: boolean;
  /** From the list row; undefined when this variant is not on the loaded page. */
  stock?: string;
  onCommitName: (nameOverride: string | null) => Promise<void>;
  onSetAttributes: (selected: Record<number, number>) => Promise<void>;
  onCreateAttribute: (name: string) => Promise<number>;
  onAddValue: (attributeId: number, value: string) => Promise<number>;
  /** The barcode section, supplied by the panel so IPC stays in one place. */
  barcodes: React.ReactNode;
}) {
  const { t } = useI18n();
  const format = useDecimalFormat();
  const [copied, setCopied] = useState(false);

  const copySku = useCallback(() => {
    const write = navigator?.clipboard?.writeText;
    if (typeof write !== 'function') return;
    void write.call(navigator.clipboard, variant.sku)
      .then(() => setCopied(true))
      .catch(() => {
        // Clipboard permission can be refused; the SKU is still readable.
      });
  }, [variant.sku]);

  return (
    <div className="sk-catalog2__veditor" data-testid={`catalog2-variant-editor-${variant.variant_id}`}>
      <div className="sk-catalog2__veditor-head">
        <h3 className="sk-catalog2__truncate" title={variant.effective_variant_name}>
          {variant.effective_variant_name}
        </h3>
        <span className={`sk-catalog2__pill ${variant.is_active ? 'sk-catalog2__pill--accent' : 'sk-catalog2__pill--neutral'}`}>
          {variant.is_active ? t('catalog.active') : t('catalog.inactive')}
        </span>
      </div>

      {/* R13: read-only identity. Click to copy, never to edit. */}
      <div className="sk-catalog2__sku-row">
        <span className="sk-catalog2__label">{t('variants.internalSku')}</span>
        <button
          type="button"
          className="sk-catalog2__sku"
          onClick={copySku}
          title={t('catalog2.copySku')}
          data-testid={`catalog2-sku-${variant.variant_id}`}
        >
          <span className="sk-catalog2__mono">{variant.sku}</span>
          <span className="sk-catalog2__sku-hint">
            {copied ? t('catalog2.copied') : t('catalog2.copySku')}
          </span>
        </button>
      </div>

      <div className="sk-catalog2__vrow-figures">
        <span>{t('variants.price')}: <strong>{format(variant.sale_price)}</strong></span>
        <span>{t('variants.minimumStock')}: <strong>{format(variant.minimum_stock)}</strong></span>
        <span>
          {t('productsList.stock')}:{' '}
          <strong>{stock !== undefined ? format(stock) : '—'}</strong>
        </span>
      </div>
      <p className="sk-catalog2__note">{t('catalog2.editFiguresInTable')}</p>

      <div className="sk-catalog2__veditor-section">
        <PanelField
          id={`catalog2-panel-variant-name-${variant.variant_id}`}
          label={t('variants.name')}
          value={variant.name_override ?? ''}
          commit={(v) => onCommitName(v || null)}
          testId={`catalog2-panel-variant-name-${variant.variant_id}`}
        />
      </div>

      <div className="sk-catalog2__veditor-section">
        <AttributeManagerForVariant
          attributes={attributes}
          refLoading={refLoading}
          variant={variant}
          onSetAttributes={onSetAttributes}
          onCreateAttribute={onCreateAttribute}
          onAddValue={onAddValue}
        />
      </div>

      <div className="sk-catalog2__veditor-section">
        <CollapsibleBarcodes count={variant.barcodes.length} variantId={variant.variant_id}>
          {barcodes}
        </CollapsibleBarcodes>
      </div>
    </div>
  );
}

/** R12 — closed by default, labelled with the count. */
function CollapsibleBarcodes({
  count,
  variantId,
  children,
}: {
  count: number;
  variantId: number;
  children: React.ReactNode;
}) {
  const { t } = useI18n();
  const [open, setOpen] = useState(false);

  return (
    <div>
      <div className="sk-catalog2__section-head">
        <h3>{t('catalog2.barcodesWithCount', { count })}</h3>
        <Button
          type="button"
          variant="secondary"
          aria-expanded={open}
          onClick={() => setOpen((prev) => !prev)}
          data-testid={`catalog2-barcodes-toggle-${variantId}`}
        >
          {open ? t('variants.collapse') : t('variants.expand')}
        </Button>
      </div>
      {open ? children : null}
    </div>
  );
}

export function VariantEditorEmpty() {
  const { t } = useI18n();
  return (
    <div className="sk-catalog2__veditor-empty" data-testid="catalog2-variant-editor-empty">
      <Banner tone="info">{t('catalog2.selectVariant')}</Banner>
    </div>
  );
}
