/**
 * WS-D-11 — the detail column: everything about ONE selected variant (R4, R6).
 *
 * This replaces the expand-in-place accordion. Before, every expanded variant
 * stacked name + identifier + status + actions + figures + attribute picker +
 * barcode section vertically inside a 560px column, several at a time, with the
 * product fields permanently above them. One variant at a time, in its own
 * column, with the product fields moved to their own tab, is the whole fix.
 *
 * WS-D-11B reorders and completes this column per the Owner's five
 * corrections (C2, C4, C5):
 *
 *   C2 — Deactivate/Activate is destructive and now lives in THIS header,
 *     acting on whichever variant is selected, instead of sitting inside a
 *     list row a user clicks to select (a misclick waiting to happen).
 *
 *   C4 — field order, top to bottom:
 *     1. Header — name, status, Deactivate
 *     2. Internal SKU (read-only, click-to-copy)
 *     3. Barcodes — collapsed-by-default toggle, count shown
 *     4. Sale price + Minimum stock (editable)
 *     5. Variant name (optional)
 *     6. Attributes — combination summary, then the chip rows
 *
 *   C5 — price and minimum stock are editable HERE as well as in the table.
 *     Both fields reuse `InlineCell`, the exact component the table's cells
 *     use — same raw-string-while-editing / formatted-while-idle behaviour,
 *     same commit-on-blur-or-Enter, same revert-on-failure — wrapped only for
 *     a form-field presentation (label above, full width) instead of the
 *     table's right-aligned cell chrome. The commit itself goes through
 *     `commitVariantFields` in `variantCommit.ts`, the SAME function the
 *     table's inline cells call — see that file and the WS-D-11B report's
 *     "Panel/table edit parity" section for the proof the two surfaces cannot
 *     build different payloads.
 *
 * R13 — the SKU is shown, visibly non-editable, with click-to-copy. It is
 * generated by `catalog._generate_sku` and must never become an input.
 * R12 — barcodes sit behind a toggle showing their count, closed by default.
 *
 * CR2 — the attribute section renders `AttributeManagerForVariant`, the
 * component that owns the `mergeAssignedValues` wiring. A retired value the
 * variant already holds keeps rendering, stays selectable and stays marked.
 * Writing a picker here instead would reintroduce that data-loss defect.
 */
import { useCallback, useState, type ReactNode } from 'react';

import { Banner, Button } from '../../shared/components';
import { useI18n } from '../../shared/i18n';
import type { AttributeDefinition, VariantDetail } from '../../shared/ipc/dto';
import { AttributeManagerForVariant } from './attributeSelection';
import { InlineCell } from './InlineCell';
import { isValidMinimumStock, isValidPrice } from './catalogValidation';
import { PanelField } from './PanelFields';
import { useDecimalFormat } from './useDecimalFormat';

/**
 * WS-D-11B — an `InlineCell` presented as a labelled form field rather than a
 * right-aligned table cell. Wraps, does not reimplement: the raw-value-while-
 * editing, commit-on-blur-or-Enter and revert-on-failure behaviour all come
 * from `InlineCell` itself.
 */
function PanelInlineCell({
  label,
  value,
  format,
  validate,
  commit,
  testId,
}: {
  label: string;
  value: string;
  format?: (value: string) => string;
  validate?: (value: string) => string | null;
  commit: (value: string) => Promise<void>;
  testId: string;
}) {
  return (
    <div className="sk-catalog2__field">
      <span className="sk-catalog2__label">{label}</span>
      <div className="sk-catalog2__panel-cell">
        <InlineCell
          value={value}
          label={label}
          format={format}
          validate={validate}
          commit={commit}
          testId={testId}
        />
      </div>
    </div>
  );
}

export function VariantEditor({
  variant,
  attributes,
  refLoading,
  stock,
  busy,
  onCommitName,
  onCommitPrice,
  onCommitMinimumStock,
  onDeactivate,
  onActivate,
  onSetAttributes,
  onCreateAttribute,
  onAddValue,
  barcodes,
  altUnits,
}: {
  variant: VariantDetail;
  attributes: AttributeDefinition[];
  refLoading: boolean;
  /** From the list row; undefined when this variant is not on the loaded page. */
  stock?: string;
  /** True while a structural action (deactivate/activate) is in flight. */
  busy: boolean;
  onCommitName: (nameOverride: string | null) => Promise<void>;
  onCommitPrice: (salePrice: string) => Promise<void>;
  onCommitMinimumStock: (minimumStock: string) => Promise<void>;
  onDeactivate: () => void;
  onActivate: () => void;
  onSetAttributes: (selected: Record<number, number>) => Promise<void>;
  onCreateAttribute: (name: string) => Promise<number>;
  onAddValue: (attributeId: number, value: string) => Promise<number>;
  /** The barcode section, supplied by the panel so IPC stays in one place. */
  barcodes: ReactNode;
  /** The alternate-units section, supplied by the panel for the same reason. */
  altUnits: ReactNode;
}) {
  const { t } = useI18n();
  const format = useDecimalFormat();
  const [copied, setCopied] = useState(false);

  const copySku = useCallback(() => {
    const write = navigator?.clipboard?.writeText;
    if (typeof write !== 'function') return;
    void write.call(navigator.clipboard, variant.sku)
      .then(() => setCopied(true))
      .catch(() => {
        // Clipboard permission can be refused; the SKU is still readable.
      });
  }, [variant.sku]);

  return (
    <div className="sk-catalog2__veditor" data-testid={`catalog2-variant-editor-${variant.variant_id}`}>
      {/* 1. Header — name, status, Deactivate (C2, C4). */}
      <div className="sk-catalog2__veditor-head">
        <h3 className="sk-catalog2__truncate" title={variant.effective_variant_name}>
          {variant.effective_variant_name}
        </h3>
        <div className="sk-catalog2__actions">
          <span className={`sk-catalog2__pill ${variant.is_active ? 'sk-catalog2__pill--accent' : 'sk-catalog2__pill--neutral'}`}>
            {variant.is_active ? t('catalog.active') : t('catalog.inactive')}
          </span>
          <Button
            type="button"
            variant={variant.is_active ? 'secondary' : 'primary'}
            loading={busy}
            onClick={variant.is_active ? onDeactivate : onActivate}
            data-testid={`catalog2-panel-variant-active-${variant.variant_id}`}
          >
            {variant.is_active ? t('variants.deactivate') : t('variants.activate')}
          </Button>
        </div>
      </div>

      {/* 2. Internal SKU (C4) — read-only identity. Click to copy, never to edit. */}
      <div className="sk-catalog2__sku-row">
        <span className="sk-catalog2__label">{t('variants.internalSku')}</span>
        <button
          type="button"
          className="sk-catalog2__sku"
          onClick={copySku}
          title={t('catalog2.copySku')}
          data-testid={`catalog2-sku-${variant.variant_id}`}
        >
          <span className="sk-catalog2__mono">{variant.sku}</span>
          <span className="sk-catalog2__sku-hint">
            {copied ? t('catalog2.copied') : t('catalog2.copySku')}
          </span>
        </button>
      </div>

      {/* 3. Barcodes (C4) — moved above pricing; collapse behaviour unchanged. */}
      <div className="sk-catalog2__veditor-section">
        <CollapsibleSection
          title={t('catalog2.barcodesWithCount', { count: variant.barcodes.length })}
          testId={`catalog2-barcodes-toggle-${variant.variant_id}`}
        >
          {barcodes}
        </CollapsibleSection>
      </div>

      {/* 3b. Alternate units (WS-D-13 Phase B) — after Barcodes and before
          pricing, per the Owner's ordering. Collapsed by default like
          Barcodes: most variants have none. */}
      <div className="sk-catalog2__veditor-section">
        <CollapsibleSection
          // `?? []`: a build running one migration behind gets no such key.
          title={t('catalog2.altUnitsWithCount', { count: (variant.alt_units ?? []).length })}
          testId={`catalog2-alt-units-toggle-${variant.variant_id}`}
        >
          {altUnits}
        </CollapsibleSection>
      </div>

      {/* 4. Sale price + Minimum stock, editable (C4, C5). Same InlineCell the
          table uses, same commitVariantFields payload underneath. */}
      <div className="sk-catalog2__veditor-section">
        <div className="sk-catalog2__panel-grid">
          <PanelInlineCell
            label={`${t('variants.price')} (DZD)`}
            value={variant.sale_price}
            format={format}
            validate={(v) => (isValidPrice(v) ? null : t('variants.invalidPrice'))}
            commit={onCommitPrice}
            testId={`catalog2-panel-price-${variant.variant_id}`}
          />
          <PanelInlineCell
            label={t('variants.minimumStock')}
            value={variant.minimum_stock}
            format={format}
            validate={(v) => (isValidMinimumStock(v) ? null : t('variants.invalidMinimumStock'))}
            commit={onCommitMinimumStock}
            testId={`catalog2-panel-min-${variant.variant_id}`}
          />
        </div>
        <p className="sk-catalog2__note">
          {t('productsList.stock')}: <strong>{stock !== undefined ? format(stock) : '—'}</strong>
        </p>
      </div>

      {/* 5. Variant name (optional) (C4). */}
      <div className="sk-catalog2__veditor-section">
        <PanelField
          id={`catalog2-panel-variant-name-${variant.variant_id}`}
          label={t('variants.name')}
          value={variant.name_override ?? ''}
          commit={(v) => onCommitName(v || null)}
          testId={`catalog2-panel-variant-name-${variant.variant_id}`}
        />
      </div>

      {/* 6. Attributes (C4) — combination summary, then chip rows (CR2). */}
      <div className="sk-catalog2__veditor-section">
        <AttributeManagerForVariant
          attributes={attributes}
          refLoading={refLoading}
          variant={variant}
          onSetAttributes={onSetAttributes}
          onCreateAttribute={onCreateAttribute}
          onAddValue={onAddValue}
        />
      </div>
    </div>
  );
}

/**
 * R12 — closed by default, labelled with a count.
 *
 * WS-D-13 Phase B generalised this from the barcodes-only version so the new
 * alternate-units section behaves identically rather than reimplementing the
 * same collapse. `testId` is passed in explicitly so the barcode toggle keeps
 * the exact id its existing regression test asserts.
 */
function CollapsibleSection({
  title,
  testId,
  children,
}: {
  title: string;
  testId: string;
  children: ReactNode;
}) {
  const { t } = useI18n();
  const [open, setOpen] = useState(false);

  return (
    <div>
      <div className="sk-catalog2__section-head">
        <h3>{title}</h3>
        <Button
          type="button"
          variant="secondary"
          aria-expanded={open}
          onClick={() => setOpen((prev) => !prev)}
          data-testid={testId}
        >
          {open ? t('variants.collapse') : t('variants.expand')}
        </Button>
      </div>
      {open ? children : null}
    </div>
  );
}

export function VariantEditorEmpty() {
  const { t } = useI18n();
  return (
    <div className="sk-catalog2__veditor-empty" data-testid="catalog2-variant-editor-empty">
      <Banner tone="info">{t('catalog2.selectVariant')}</Banner>
    </div>
  );
}
