#![allow(dead_code)]
mod application;
pub mod commands;
#[cfg_attr(not(test), allow(dead_code))]
mod domain;
mod error;
mod infrastructure;
pub mod state;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(state::AppState {
            stage: "Slice 4".to_string(),
        })
        .manage(tauri::async_runtime::block_on(async {
            infrastructure::db::database_state_from_env()
        }))
        .invoke_handler(tauri::generate_handler![
            commands::app_info::get_app_info,
            commands::db_health::check_db_health,
            commands::auth::login,
            commands::auth::logout,
            commands::stock_receipt::post_stock_receipt,
            commands::stock_adjustment::confirm_stock_adjustment,
            commands::stock_adjustment::list_stock_adjustment_units,
            commands::cash_sale::confirm_cash_sale,
            commands::credit_sale::confirm_credit_sale,
            commands::credit_sale::authorize_credit_override,
            commands::cash_session::open_cash_session,
            commands::cash_session::inspect_active_cash_session,
            commands::cash_session::inspect_current_cash_session,
            commands::cash_session::list_cash_denominations,
            commands::cash_session::begin_cash_session_close,
            commands::cash_session::cancel_cash_session_close,
            commands::cash_session::submit_cash_session_count,
            commands::cash_session::approve_cash_session_variance,
            commands::cash_session::suspend_cash_session,
            commands::cash_session::resume_cash_session,
            commands::cash_session::handover_cash_session,
            commands::cash_session::get_cash_session,
            commands::drawer::list_drawer_operation_policy,
            commands::drawer::update_drawer_operation_policy,
            commands::onboarding::get_historical_finance_setting,
            commands::onboarding::update_historical_finance_setting,
            commands::onboarding::create_historical_finance_batch,
            commands::onboarding::replace_historical_finance_batch_data,
            commands::onboarding::validate_historical_finance_batch,
            commands::onboarding::approve_historical_finance_batch,
            commands::onboarding::get_historical_finance_summary,
            commands::opening_state::get_opening_state_setting,
            commands::opening_state::update_opening_state_setting,
            commands::opening_state::create_opening_state_package,
            commands::opening_state::replace_opening_state_package_data,
            commands::opening_state::validate_opening_state_package,
            commands::opening_state::approve_opening_state_package,
            commands::opening_state::get_opening_state_package,
            commands::opening_state_lifecycle::get_opening_state_onboarding_status,
            commands::opening_state_lifecycle::set_opening_state_onboarding_choice,
            commands::opening_state_application::get_opening_state_application_context,
            commands::opening_state_application::update_opening_state_application_setting,
            commands::opening_state_application::apply_opening_state,
            commands::recovery::get_restore_verification_setting,
            commands::recovery::update_restore_verification_setting,
            commands::recovery::create_operator_backup,
            commands::recovery::validate_operator_backup,
            commands::recovery::verify_operator_backup_restore,
            commands::setup::get_setup_status,
            commands::setup::bootstrap_first_admin,
            commands::catalog::create_product,
            commands::catalog::list_products,
            commands::catalog::create_product_with_variants,
            commands::catalog::add_variant,
            commands::catalog::update_variant,
            commands::catalog::set_variant_active,
            commands::catalog::update_product,
            commands::catalog::create_attribute,
            commands::catalog::add_attribute_value,
            commands::catalog::list_attributes,
            commands::catalog::create_unit,
            commands::catalog::list_units,
            commands::catalog::set_variant_attributes,
            commands::catalog::add_variant_barcode,
            commands::catalog::remove_variant_barcode,
            commands::catalog::add_variant_alt_unit,
            commands::catalog::remove_variant_alt_unit,
            commands::catalog::set_variant_base_unit,
            commands::catalog::resolve_barcode,
            commands::catalog::list_catalog_products,
            commands::catalog::get_product_detail,
            commands::warehouse::create_warehouse,
            commands::warehouse::list_warehouses,
            commands::reference::list_fiscal_periods,
            commands::reference::get_open_fiscal_period,
            commands::reference::get_dashboard_summary,
            commands::documents::get_sale_document,
            commands::documents::list_sale_lines,
            commands::documents::list_document_jobs,
            commands::documents::list_printable_documents,
            commands::documents::get_customer_document_payload,
            commands::documents::generate_customer_document_pdf,
            commands::documents::enqueue_customer_reprint,
            commands::procurement::create_supplier,
            commands::procurement::update_supplier,
            commands::procurement::list_suppliers,
            commands::procurement::create_purchase_order_draft,
            commands::procurement::update_purchase_order_draft,
            commands::procurement::confirm_purchase_order,
            commands::procurement::cancel_purchase_order,
            commands::procurement::list_purchase_orders,
            commands::procurement::get_purchase_order_detail,
            commands::procurement::confirm_purchase_receipt,
            commands::procurement::list_purchase_receipts,
            commands::procurement::allocate_landed_cost,
            commands::procurement::create_supplier_invoice_draft,
            commands::procurement::confirm_supplier_invoice,
            commands::procurement::list_supplier_invoices,
            commands::procurement::list_supplier_liabilities,
            commands::procurement::create_supplier_return_draft,
            commands::procurement::confirm_supplier_return,
            commands::procurement::post_supplier_payment,
            commands::procurement::list_supplier_returns,
            commands::procurement::list_supplier_payments,
            commands::customer::create_customer,
            commands::customer::update_customer,
            commands::customer::list_customers,
            commands::customer::get_customer_capabilities,
            commands::customer::get_customer_credit_summary,
            commands::customer::list_customer_ledger,
            commands::receivables::list_open_customer_invoices,
            commands::receivables::post_customer_payment,
            commands::receivables::list_refundable_customer_payments,
            commands::receivables::authorize_customer_payment_refund,
            commands::receivables::post_customer_refund,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
