import type { Locale } from '../../shared/i18n';

export type ProcurementCopy = {
  refresh: string;
  cancel: string;
  close: string;
  loading: string;
  actions: string;
  status: string;
  supplier: string;
  warehouse: string;
  purchaseOrder: string;
  receipt: string;
  document: string;
  journal: string;
  amount: string;
  date: string;
  note: string;
  product: string;
  quantity: string;
  unitCost: string;
  total: string;
  createInvoice: string;
  invoiceTitle: string;
  invoiceEmpty: string;
  invoiceDraftCreated: string;
  invoiceConfirmed: string;
  confirmInvoice: string;
  receiptLine: string;
  availableToInvoice: string;
  noInvoiceLines: string;
  landedCost: string;
  allocateLandedCost: string;
  allocationMethod: string;
  byQuantity: string;
  byValue: string;
  equalPerLine: string;
  landedCostPosted: string;
  alreadyAllocated: string;
  noReceipts: string;
  receiptsTitle: string;
  returnTitle: string;
  returnSubtitle: string;
  newReturn: string;
  returnEmpty: string;
  returnDraftCreated: string;
  returnConfirmed: string;
  confirmReturn: string;
  reason: string;
  defective: string;
  excess: string;
  wrongItem: string;
  returnable: string;
  payablesTitle: string;
  outstandingTotal: string;
  noPayables: string;
  originalAmount: string;
  outstanding: string;
  dueDate: string;
  paySupplier: string;
  paymentAmount: string;
  paymentMethod: string;
  cash: string;
  bank: string;
  check: string;
  paymentPosted: string;
  paymentHistory: string;
  noPayments: string;
  processing: string;
  confirmPayment: string;
  openPeriodRequired: string;
  requestUncertain: string;
  quantityExceedsAvailable: string;
  quantityExceedsReturnable: string;
  paymentExceedsOutstanding: string;
  receiptJournal: string;
  clearing: string;
  inventoryValue: string;
  variance: string;
  code: string;
  name: string;
  contact: string;
  phone: string;
  email: string;
  taxId: string;
  address: string;
  active: string;
  inactive: string;
  edit: string;
  activate: string;
  deactivate: string;
  newSupplier: string;
  editSupplier: string;
  newPurchaseOrder: string;
  createPurchaseOrderDraft: string;
  destinationWarehouse: string;
  orderLines: string;
  purchasedItems: string;
  unit: string;
  subtotalPreview: string;
  addLine: string;
  remove: string;
  saveDraft: string;
  poNumber: string;
  created: string;
  view: string;
  confirmOrder: string;
  receiveGoods: string;
  cancelOrder: string;
  orderDetail: string;
  ordered: string;
  received: string;
  remaining: string;
  confirmGoodsReceipt: string;
  receiptDate: string;
  receiveNow: string;
  previouslyReceived: string;
  confirming: string;
  optionalNote: string;
  newPurchase: string;
  confirmPurchase: string;
  purchaseConfirmed: string;
  purchasesTitle: string;
  purchaseNumber: string;
  directPurchase: string;
  purchaseOrderOrigin: string;
  origin: string;
  searchReceiptsPlaceholder: string;
  allOrigins: string;
  allSuppliers: string;
  allWarehouses: string;
  totalReceipts: string;
  totalValue: string;
  directPurchases: string;
  viewDetails: string;
  receiptDetail: string;
  accountingImpact: string;
  inventoryMerchandise: string;
  grniAccount: string;
  balancedJournal: string;
  viewJournal: string;
  exportXlsx: string;
  noReceiptsSubtitle: string;
  retry: string;
  chooseItem: string;
  searchItemsPlaceholder: string;
  scanBarcodePlaceholder: string;
  barcodeNotFound: string;
  itemAlreadyAdded: string;
  noItemsFound: string;
  dateFrom: string;
  dateTo: string;
  printReceipt: string;
  filters: string;
  clearFilters: string;
  costRange: string;
  minCost: string;
  maxCost: string;
  allUnits: string;
  attributes: string;
  brand: string;
  allBrands: string;
  payment: string;
  recordPayment: string;
  paymentReference: string;
  paymentAmountInvalid: string;
  methodCash: string;
  methodBankTransfer: string;
  payLater: string;
  balanceDue: string;
  statusPaid: string;
  statusPartiallyPaid: string;
  statusUnpaid: string;
  totalSuppliers: string;
  activeSuppliers: string;
  searchSuppliersPlaceholder: string;
  autoGenerated: string;
  codeLocked: string;
  suppliersTitle: string;
  printA4: string;
  downloadPdf: string;
  returnToSupplier: string;
  returnPosted: string;
  returnReason: string;
  reasonDefective: string;
  reasonExcess: string;
  reasonWrongItem: string;
  reasonOther: string;
  supplierRefNote: string;
  noteRequiredForOther: string;
  optional: string;
  quantityReturnable: string;
  quantityToReturn: string;
  refundPreview: string;
  returnNeedsLine: string;
  returned: string;
  supplierOwesYou: string;
};

export const PROCUREMENT_COPY: Record<Locale, ProcurementCopy> = {
  en: {
    newPurchase: 'New purchase', confirmPurchase: 'Confirm purchase', purchaseConfirmed: 'Direct purchase posted successfully.',
    purchasesTitle: 'Purchases & goods receipts', purchaseNumber: 'Purchase #',
    directPurchase: 'Direct Purchase', purchaseOrderOrigin: 'Purchase Order', origin: 'Origin',
    searchReceiptsPlaceholder: 'Search receipt #, supplier, journal…',
    allOrigins: 'All origins', allSuppliers: 'All suppliers', allWarehouses: 'All warehouses',
    totalReceipts: 'Total Receipts', totalValue: 'Total Value', directPurchases: 'Direct Purchases',
    viewDetails: 'View details', receiptDetail: 'Purchase Receipt Detail', accountingImpact: 'Accounting Impact',
    inventoryMerchandise: 'Inventory Merchandise (Debit)', grniAccount: 'Goods Received Not Invoiced (Credit)',
    balancedJournal: 'Balanced Entry (Debit = Credit)', viewJournal: 'View Journal',
    exportXlsx: 'Export Excel (.xlsx)',
    noReceiptsSubtitle: 'Confirmed Direct Purchases and physical goods receipts will appear here.',
    retry: 'Retry',
    refresh: 'Refresh', cancel: 'Cancel', close: 'Close', loading: 'Loading…', actions: 'Actions',
    status: 'Status', supplier: 'Supplier', warehouse: 'Warehouse', purchaseOrder: 'Purchase order',
    receipt: 'Receipt', document: 'Document', journal: 'Journal', amount: 'Amount', date: 'Date',
    note: 'Supplier reference / note (optional)', product: 'Product / variant', quantity: 'Quantity', unitCost: 'Unit cost', total: 'Total',
    createInvoice: 'New supplier invoice', invoiceTitle: 'Supplier invoices', invoiceEmpty: 'No supplier invoices found.',
    invoiceDraftCreated: 'Supplier invoice draft created.', invoiceConfirmed: 'Supplier invoice posted.',
    confirmInvoice: 'Confirm invoice', receiptLine: 'Matched receipt line', availableToInvoice: 'Available to invoice',
    noInvoiceLines: 'No uninvoiced receipt lines are available for this purchase order.', landedCost: 'Landed cost',
    allocateLandedCost: 'Allocate landed cost', allocationMethod: 'Allocation method', byQuantity: 'By received quantity',
    byValue: 'By receipt value', equalPerLine: 'Equal per line', landedCostPosted: 'Landed cost posted.',
    alreadyAllocated: 'Already allocated', noReceipts: 'No purchase receipts yet', receiptsTitle: 'Purchase Receipts & History',
    returnTitle: 'Supplier returns & debit notes', returnSubtitle: 'Return received goods through an auditable stock and accounting posting.',
    newReturn: 'New return', returnEmpty: 'No supplier returns found.', returnDraftCreated: 'Supplier return draft created.',
    returnConfirmed: 'Supplier return posted.', confirmReturn: 'Confirm return', reason: 'Reason', defective: 'Defective / damaged goods',
    excess: 'Excess delivery', wrongItem: 'Wrong item', returnable: 'Returnable quantity', payablesTitle: 'Supplier payables',
    outstandingTotal: 'Total outstanding', noPayables: 'No open supplier payables.', originalAmount: 'Original amount',
    outstanding: 'Outstanding', dueDate: 'Due date', paySupplier: 'Pay supplier', paymentAmount: 'Amount paid',
    paymentMethod: 'Payment method', cash: 'Cash', bank: 'Bank transfer', check: 'Check', paymentPosted: 'Payment recorded',
    paymentHistory: 'Payment history', noPayments: 'No supplier payments found.', processing: 'Processing…',
    confirmPayment: 'Confirm payment', openPeriodRequired: 'An open fiscal period is required.',
    requestUncertain: 'The request was not confirmed. Retry uses the same request identity.', receiptJournal: 'Receipt journal',
    quantityExceedsAvailable: 'Invoice quantity cannot exceed the uninvoiced receipt quantity.',
    quantityExceedsReturnable: 'Return quantity cannot exceed the net received quantity.',
    paymentExceedsOutstanding: 'Payment cannot exceed the selected outstanding liability.',
    clearing: 'Clearing', inventoryValue: 'Inventory value', variance: 'Variance', code: 'Code', name: 'Name',
    contact: 'Contact', phone: 'Phone', email: 'Email', taxId: 'Tax ID (NIF / NIS)', address: 'Address',
    active: 'Active', inactive: 'Inactive', edit: 'Edit', activate: 'Activate', deactivate: 'Deactivate',
    newSupplier: 'New supplier', editSupplier: 'Edit supplier', newPurchaseOrder: 'New purchase order',
    createPurchaseOrderDraft: 'Create purchase order draft', destinationWarehouse: 'Destination warehouse', orderLines: 'Order lines', purchasedItems: 'Purchased items', unit: 'Unit',
    subtotalPreview: 'Subtotal preview', addLine: 'Add line', remove: 'Remove', saveDraft: 'Save draft', poNumber: 'PO number', created: 'Created',
    view: 'View', confirmOrder: 'Confirm order', receiveGoods: 'Receive goods', cancelOrder: 'Cancel order', orderDetail: 'Purchase order detail',
    ordered: 'Ordered', received: 'Received', remaining: 'Remaining', confirmGoodsReceipt: 'Confirm goods receipt', receiptDate: 'Receipt date',
    receiveNow: 'Receive now', previouslyReceived: 'Previously received', confirming: 'Confirming…', optionalNote: 'Optional purchase-order note',
    chooseItem: 'Choose item',
    searchItemsPlaceholder: 'Search by name, SKU or barcode',
    scanBarcodePlaceholder: 'Scan barcode, then Enter',
    barcodeNotFound: 'No product matches this barcode',
    itemAlreadyAdded: 'Already added to this purchase',
    noItemsFound: 'No matching products',
    dateFrom: 'From',
    dateTo: 'To',
    printReceipt: 'Print',
    filters: 'Filters',
    clearFilters: 'Clear all',
    costRange: 'Cost range (DZD)',
    minCost: 'Min',
    maxCost: 'Max',
    allUnits: 'All units',
    attributes: 'Attributes',
    brand: 'Brand',
    allBrands: 'All brands',
    payment: 'Payment',
    recordPayment: 'Record payment',
    paymentReference: 'Reference (optional)',
    paymentAmountInvalid: 'Enter an amount greater than zero, for example 1000 or 1000.00.',
    methodCash: 'Cash',
    methodBankTransfer: 'Bank transfer',
    payLater: 'Pay later',
    balanceDue: 'Balance due',
    statusPaid: 'Paid',
    statusPartiallyPaid: 'Partly paid',
    statusUnpaid: 'Unpaid',
    totalSuppliers: 'Total Suppliers',
    activeSuppliers: 'Active Suppliers',
    searchSuppliersPlaceholder: 'Search by code, name, contact, phone…',
    autoGenerated: 'Auto-generated',
    codeLocked: 'Code cannot be changed',
    suppliersTitle: 'Supplier directory & balances',
    printA4: 'Print A4',
    downloadPdf: 'Download PDF',
    returnToSupplier: 'Return to supplier',
    returnPosted: 'Return recorded',
    returnReason: 'Reason',
    reasonDefective: 'Damaged or defective',
    reasonExcess: 'Delivered in excess',
    reasonWrongItem: 'Wrong item',
    reasonOther: 'Other',
    supplierRefNote: 'Supplier reference / note',
    noteRequiredForOther: 'Supplier reference / note is required when reason is Other.',
    optional: 'optional',
    quantityReturnable: 'Can return',
    quantityToReturn: 'Return quantity',
    refundPreview: 'Supplier credit',
    returnNeedsLine: 'Enter a quantity on at least one line.',
    returned: 'Returned',
    supplierOwesYou: 'Supplier owes you',
  },
  fr: {
    newPurchase: 'Nouvel achat', confirmPurchase: 'Confirmer l’achat', purchaseConfirmed: 'Achat direct enregistré avec succès.',
    purchasesTitle: 'Achats et réceptions de marchandises', purchaseNumber: 'N° Achat',
    directPurchase: 'Achat direct', purchaseOrderOrigin: 'Commande d’achat', origin: 'Origine',
    searchReceiptsPlaceholder: 'Rechercher n° réception, fournisseur, journal…',
    allOrigins: 'Toutes origines', allSuppliers: 'Tous les fournisseurs', allWarehouses: 'Tous les dépôts',
    totalReceipts: 'Total Réceptions', totalValue: 'Valeur Totale', directPurchases: 'Achats Directs',
    viewDetails: 'Voir détails', receiptDetail: 'Détail du Bon de Réception', accountingImpact: 'Impact Comptable',
    inventoryMerchandise: 'Stock Marchandises (Débit)', grniAccount: 'Factures Non Parvenues / FNP (Crédit)',
    balancedJournal: 'Écriture Équilibrée (Débit = Crédit)', viewJournal: 'Voir le journal',
    exportXlsx: 'Exporter Excel (.xlsx)',
    noReceiptsSubtitle: 'Les achats directs confirmés et les réceptions de marchandises apparaîtront ici.',
    retry: 'Réessayer',
    refresh: 'Actualiser', cancel: 'Annuler', close: 'Fermer', loading: 'Chargement…', actions: 'Actions',
    status: 'Statut', supplier: 'Fournisseur', warehouse: 'Dépôt', purchaseOrder: "Commande d’achat",
    receipt: 'Réception', document: 'Document', journal: 'Journal', amount: 'Montant', date: 'Date',
    note: 'Référence fournisseur / note (facultatif)', product: 'Produit / variante', quantity: 'Quantité', unitCost: 'Coût unitaire', total: 'Total',
    createInvoice: 'Nouvelle facture fournisseur', invoiceTitle: 'Factures fournisseurs', invoiceEmpty: 'Aucune facture fournisseur.',
    invoiceDraftCreated: 'Brouillon de facture créé.', invoiceConfirmed: 'Facture fournisseur comptabilisée.',
    confirmInvoice: 'Confirmer la facture', receiptLine: 'Ligne de réception rapprochée', availableToInvoice: 'Disponible à facturer',
    noInvoiceLines: 'Aucune ligne de réception non facturée pour cette commande.', landedCost: 'Frais d’approche',
    allocateLandedCost: 'Affecter les frais d’approche', allocationMethod: 'Méthode de répartition', byQuantity: 'Selon la quantité reçue',
    byValue: 'Selon la valeur reçue', equalPerLine: 'Répartition égale', landedCostPosted: 'Frais d’approche comptabilisés.',
    alreadyAllocated: 'Déjà affectés', noReceipts: 'Aucun bon de réception pour le moment', receiptsTitle: 'Bons de Réception et Historique',
    returnTitle: 'Retours fournisseurs et notes de débit', returnSubtitle: 'Retourner les marchandises reçues avec une écriture stock et comptable traçable.',
    newReturn: 'Nouveau retour', returnEmpty: 'Aucun retour fournisseur.', returnDraftCreated: 'Brouillon de retour créé.',
    returnConfirmed: 'Retour fournisseur comptabilisé.', confirmReturn: 'Confirmer le retour', reason: 'Motif', defective: 'Marchandise défectueuse / endommagée',
    excess: 'Livraison excédentaire', wrongItem: 'Article incorrect', returnable: 'Quantité retournable', payablesTitle: 'Dettes fournisseurs',
    outstandingTotal: 'Total restant', noPayables: 'Aucune dette fournisseur ouverte.', originalAmount: 'Montant initial',
    outstanding: 'Reste à payer', dueDate: 'Échéance', paySupplier: 'Payer le fournisseur', paymentAmount: 'Montant payé',
    paymentMethod: 'Mode de paiement', cash: 'Espèces', bank: 'Virement bancaire', check: 'Chèque', paymentPosted: 'Paiement enregistré',
    paymentHistory: 'Historique des paiements', noPayments: 'Aucun paiement fournisseur.', processing: 'Traitement…',
    confirmPayment: 'Confirmer le paiement', openPeriodRequired: 'Une période comptable ouverte est requise.',
    requestUncertain: 'La demande n’a pas été confirmée. Une nouvelle tentative réutilise la même identité.', receiptJournal: 'Journal de réception',
    quantityExceedsAvailable: 'La quantité facturée ne peut pas dépasser la quantité reçue non facturée.',
    quantityExceedsReturnable: 'La quantité retournée ne peut pas dépasser la quantité nette reçue.',
    paymentExceedsOutstanding: 'Le paiement ne peut pas dépasser la dette sélectionnée restante.',
    clearing: 'Apurement', inventoryValue: 'Valeur du stock', variance: 'Écart', code: 'Code', name: 'Nom',
    contact: 'Contact', phone: 'Téléphone', email: 'E-mail', taxId: 'Identifiant fiscal (NIF / NIS)', address: 'Adresse',
    active: 'Actif', inactive: 'Inactif', edit: 'Modifier', activate: 'Activer', deactivate: 'Désactiver',
    newSupplier: 'Nouveau fournisseur', editSupplier: 'Modifier le fournisseur', newPurchaseOrder: "Nouvelle commande d’achat",
    createPurchaseOrderDraft: "Créer un brouillon de commande", destinationWarehouse: 'Dépôt de destination', orderLines: 'Lignes de commande', purchasedItems: 'Articles achetés', unit: 'Unité',
    subtotalPreview: 'Sous-total provisoire', addLine: 'Ajouter une ligne', remove: 'Retirer', saveDraft: 'Enregistrer le brouillon', poNumber: 'N° commande', created: 'Créée le',
    view: 'Voir', confirmOrder: 'Confirmer la commande', receiveGoods: 'Réceptionner', cancelOrder: 'Annuler la commande', orderDetail: 'Détail de la commande',
    ordered: 'Commandé', received: 'Reçu', remaining: 'Restant', confirmGoodsReceipt: 'Confirmer la réception', receiptDate: 'Date de réception',
    receiveNow: 'Réception actuelle', previouslyReceived: 'Déjà reçu', confirming: 'Confirmation…', optionalNote: 'Note facultative de commande',
    chooseItem: 'Choisir un article',
    searchItemsPlaceholder: 'Rechercher par nom, SKU ou code-barres',
    scanBarcodePlaceholder: 'Scanner le code-barres, puis Entrée',
    barcodeNotFound: 'Aucun produit ne correspond à ce code-barres',
    itemAlreadyAdded: 'Déjà ajouté à cet achat',
    noItemsFound: 'Aucun produit correspondant',
    dateFrom: 'Du',
    dateTo: 'Au',
    printReceipt: 'Imprimer',
    filters: 'Filtres',
    clearFilters: 'Effacer tout',
    costRange: 'Fourchette de coût (DZD)',
    minCost: 'Min',
    maxCost: 'Max',
    allUnits: 'Toutes les unités',
    attributes: 'Attributs',
    brand: 'Marque',
    allBrands: 'Toutes les marques',
    payment: 'Paiement',
    recordPayment: 'Enregistrer un paiement',
    paymentReference: 'Référence (facultatif)',
    paymentAmountInvalid: 'Saisissez un montant supérieur à zéro, par exemple 1000 ou 1000.00.',
    methodCash: 'Espèces',
    methodBankTransfer: 'Virement bancaire',
    payLater: 'Payer plus tard',
    balanceDue: 'Solde dû',
    statusPaid: 'Payé',
    statusPartiallyPaid: 'Partiellement payé',
    statusUnpaid: 'Non payé',
    totalSuppliers: 'Total Fournisseurs',
    activeSuppliers: 'Fournisseurs Actifs',
    searchSuppliersPlaceholder: 'Rechercher code, nom, contact, tél…',
    autoGenerated: 'Généré automatiquement',
    codeLocked: 'Le code ne peut pas être modifié',
    suppliersTitle: 'Répertoire et créances fournisseurs',
    printA4: 'Imprimer A4',
    downloadPdf: 'Télécharger PDF',
    returnToSupplier: 'Retour fournisseur',
    returnPosted: 'Retour enregistré',
    returnReason: 'Motif',
    reasonDefective: 'Endommagé ou défectueux',
    reasonExcess: 'Livré en excès',
    reasonWrongItem: 'Article incorrect',
    reasonOther: 'Autre',
    supplierRefNote: 'Référence fournisseur / note',
    noteRequiredForOther: 'La référence fournisseur / note est requise lorsque le motif est Autre.',
    optional: 'facultatif',
    quantityReturnable: 'Retournable',
    quantityToReturn: 'Quantité à retourner',
    refundPreview: 'Avoir fournisseur',
    returnNeedsLine: 'Saisissez une quantité sur au moins une ligne.',
    returned: 'Retourné',
    supplierOwesYou: 'Le fournisseur vous doit',
  },
  ar: {
    newPurchase: 'شراء جديد', confirmPurchase: 'تأكيد الشراء', purchaseConfirmed: 'تم تسجيل الشراء المباشر بنجاح.',
    purchasesTitle: 'المشتريات واستلام البضائع', purchaseNumber: 'رقم الشراء',
    directPurchase: 'شراء مباشر', purchaseOrderOrigin: 'أمر شراء', origin: 'المصدر',
    searchReceiptsPlaceholder: 'بحث برقم الاستلام، المورد، القيد…',
    allOrigins: 'جميع المصادر', allSuppliers: 'جميع الموردين', allWarehouses: 'جميع المخازن',
    totalReceipts: 'إجمالي الاستلامات', totalValue: 'القيمة الإجمالية', directPurchases: 'المشتريات المباشرة',
    viewDetails: 'عرض التفاصيل', receiptDetail: 'تفاصيل وصل الاستلام', accountingImpact: 'الأثر المحاسبي',
    inventoryMerchandise: 'مخزون البضائع (مدين)', grniAccount: 'بضاعة مستلمة غير مفوترة (دائن)',
    balancedJournal: 'قيد متوازن (مدين = دائن)', viewJournal: 'عرض القيد',
    exportXlsx: 'تصدير إكسل (.xlsx)',
    noReceiptsSubtitle: 'ستظهر هنا المشتريات المباشرة المؤكدة واستلامات البضائع الفعلية.',
    retry: 'إعادة المحاولة',
    refresh: 'تحديث', cancel: 'إلغاء', close: 'إغلاق', loading: 'جارٍ التحميل…', actions: 'الإجراءات',
    status: 'الحالة', supplier: 'المورد', warehouse: 'المخزن', purchaseOrder: 'أمر الشراء',
    receipt: 'الاستلام', document: 'المستند', journal: 'القيد', amount: 'المبلغ', date: 'التاريخ',
    note: 'مرجع المورد / ملاحظة (اختياري)', product: 'المنتج / الصنف', quantity: 'الكمية', unitCost: 'تكلفة الوحدة', total: 'المجموع',
    createInvoice: 'فاتورة مورد جديدة', invoiceTitle: 'فواتير الموردين', invoiceEmpty: 'لا توجد فواتير موردين.',
    invoiceDraftCreated: 'تم إنشاء مسودة فاتورة المورد.', invoiceConfirmed: 'تم ترحيل فاتورة المورد.',
    confirmInvoice: 'تأكيد الفاتورة', receiptLine: 'سطر الاستلام المطابق', availableToInvoice: 'المتاح للفوترة',
    noInvoiceLines: 'لا توجد أسطر استلام غير مفوترة لهذا الأمر.', landedCost: 'تكاليف الاستيراد والنقل',
    allocateLandedCost: 'توزيع التكاليف الإضافية', allocationMethod: 'طريقة التوزيع', byQuantity: 'حسب الكمية المستلمة',
    byValue: 'حسب قيمة الاستلام', equalPerLine: 'بالتساوي على الأسطر', landedCostPosted: 'تم ترحيل التكاليف الإضافية.',
    alreadyAllocated: 'موزعة مسبقاً', noReceipts: 'لا توجد وصولات استلام حتى الآن', receiptsTitle: 'وصولات الاستلام والسجل',
    returnTitle: 'مرتجعات الموردين وإشعارات الخصم', returnSubtitle: 'إرجاع البضاعة المستلمة مع حركة مخزون وقيد محاسبي قابلين للتتبع.',
    newReturn: 'مرتجع جديد', returnEmpty: 'لا توجد مرتجعات موردين.', returnDraftCreated: 'تم إنشاء مسودة المرتجع.',
    returnConfirmed: 'تم ترحيل مرتجع المورد.', confirmReturn: 'تأكيد المرتجع', reason: 'السبب', defective: 'بضاعة تالفة / معيبة',
    excess: 'كمية زائدة', wrongItem: 'صنف خاطئ', returnable: 'الكمية القابلة للإرجاع', payablesTitle: 'ديون الموردين',
    outstandingTotal: 'إجمالي المتبقي', noPayables: 'لا توجد ديون موردين مفتوحة.', originalAmount: 'المبلغ الأصلي',
    outstanding: 'المتبقي', dueDate: 'تاريخ الاستحقاق', paySupplier: 'دفع للمورد', paymentAmount: 'المبلغ المدفوع',
    paymentMethod: 'طريقة الدفع', cash: 'نقداً', bank: 'تحويل بنكي', check: 'شيك', paymentPosted: 'تم تسجيل الدفعة',
    paymentHistory: 'سجل الدفعات', noPayments: 'لا توجد دفعات موردين.', processing: 'جارٍ التنفيذ…',
    confirmPayment: 'تأكيد الدفع', openPeriodRequired: 'يجب توفر فترة محاسبية مفتوحة.',
    requestUncertain: 'لم يتم تأكيد الطلب. ستستخدم المحاولة الجديدة نفس معرّف الطلب.', receiptJournal: 'قيد الاستلام',
    quantityExceedsAvailable: 'لا يمكن أن تتجاوز كمية الفاتورة كمية الاستلام غير المفوترة.',
    quantityExceedsReturnable: 'لا يمكن أن تتجاوز كمية المرتجع صافي الكمية المستلمة.',
    paymentExceedsOutstanding: 'لا يمكن أن تتجاوز الدفعة الدين المتبقي المحدد.',
    clearing: 'التسوية', inventoryValue: 'قيمة المخزون', variance: 'الفرق', code: 'الرمز', name: 'الاسم',
    contact: 'جهة الاتصال', phone: 'الهاتف', email: 'البريد الإلكتروني', taxId: 'المعرف الجبائي (NIF / NIS)', address: 'العنوان',
    active: 'نشط', inactive: 'غير نشط', edit: 'تعديل', activate: 'تفعيل', deactivate: 'تعطيل',
    newSupplier: 'مورد جديد', editSupplier: 'تعديل المورد', newPurchaseOrder: 'أمر شراء جديد',
    createPurchaseOrderDraft: 'إنشاء مسودة أمر شراء', destinationWarehouse: 'المخزن المستلم', orderLines: 'أسطر الطلب', purchasedItems: 'الأصناف المشتراة', unit: 'الوحدة',
    subtotalPreview: 'المجموع الفرعي المبدئي', addLine: 'إضافة سطر', remove: 'حذف', saveDraft: 'حفظ المسودة', poNumber: 'رقم أمر الشراء', created: 'تاريخ الإنشاء',
    view: 'عرض', confirmOrder: 'تأكيد الأمر', receiveGoods: 'استلام البضاعة', cancelOrder: 'إلغاء الأمر', orderDetail: 'تفاصيل أمر الشراء',
    ordered: 'المطلوب', received: 'المستلم', remaining: 'المتبقي', confirmGoodsReceipt: 'تأكيد استلام البضاعة', receiptDate: 'تاريخ الاستلام',
    receiveNow: 'الكمية المستلمة الآن', previouslyReceived: 'المستلم سابقاً', confirming: 'جارٍ التأكيد…', optionalNote: 'ملاحظة اختيارية لأمر الشراء',
    chooseItem: 'اختيار صنف',
    searchItemsPlaceholder: 'البحث بالاسم أو الرمز أو الباركود',
    scanBarcodePlaceholder: 'امسح الباركود ثم اضغط Enter',
    barcodeNotFound: 'لا يوجد منتج مطابق لهذا الباركود',
    itemAlreadyAdded: 'مضاف مسبقاً إلى هذا الشراء',
    noItemsFound: 'لا توجد منتجات مطابقة',
    dateFrom: 'من',
    dateTo: 'إلى',
    printReceipt: 'طباعة',
    filters: 'عوامل التصفية',
    clearFilters: 'إعادة ضبط',
    costRange: 'نطاق التكلفة (دج)',
    minCost: 'الحد الأدنى',
    maxCost: 'الحد الأقصى',
    allUnits: 'جميع الوحدات',
    attributes: 'السمات',
    brand: 'العلامة التجارية',
    allBrands: 'جميع العلامات',
    payment: 'الدفع',
    recordPayment: 'تسجيل دفعة',
    paymentReference: 'المرجع (اختياري)',
    paymentAmountInvalid: 'أدخل مبلغاً أكبر من صفر، مثال 1000 أو 1000.00.',
    methodCash: 'نقداً',
    methodBankTransfer: 'تحويل بنكي',
    payLater: 'الدفع لاحقاً',
    balanceDue: 'الرصيد المستحق',
    statusPaid: 'مدفوع',
    statusPartiallyPaid: 'مدفوع جزئياً',
    statusUnpaid: 'غير مدفوع',
    totalSuppliers: 'إجمالي الموردين',
    activeSuppliers: 'الموردون النشطون',
    searchSuppliersPlaceholder: 'بحث بالكود، الاسم، جهة الاتصال، الهاتف…',
    autoGenerated: 'توليد تلقائي',
    codeLocked: 'لا يمكن تعديل الكود',
    suppliersTitle: 'دليل الموردين والديون',
    printA4: 'طباعة A4',
    downloadPdf: 'تحميل PDF',
    returnToSupplier: 'إرجاع للمورد',
    returnPosted: 'تم تسجيل الإرجاع',
    returnReason: 'السبب',
    reasonDefective: 'تالف أو معيب',
    reasonExcess: 'كمية زائدة',
    reasonWrongItem: 'صنف خاطئ',
    reasonOther: 'أخرى',
    supplierRefNote: 'مرجع المورد / ملاحظة',
    noteRequiredForOther: 'مرجع المورد / الملاحظة مطلوبة عندما يكون السبب أخرى.',
    optional: 'اختياري',
    quantityReturnable: 'القابل للإرجاع',
    quantityToReturn: 'الكمية المرجعة',
    refundPreview: 'رصيد لدى المورد',
    returnNeedsLine: 'أدخل كمية في سطر واحد على الأقل.',
    returned: 'مُرجع',
    supplierOwesYou: 'المورد مدين لك',
  },
};
